#packmode mythic beast
#modloaded extendedcrafting avaritia

//neutronium compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
//ultimate stew
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);
mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:ultimate_stew> * 3, [<avaritia:resource:3>, <ore:toolPot>, <ore:foodStock>, <ore:foodChickendinner>, <ore:cropRice>, <ore:cropBean>, <ore:foodSpicygreens>, <ore:cropTomato>, <ore:cropPotato>]);
//endest pearl
mods.avaritia.ExtremeCrafting.remove(<avaritia:endest_pearl>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:endest_pearl>, [[null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null]]);
//planet eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_shovel>, [[null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null], [<ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null, null]]);
//World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_pickaxe>, [[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotInfinity>, null, null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);
//hoe of green earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_hoe>, [[null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null]]);
//longbow of the heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_bow>, [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:blockCrystalMatrix>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null]]);
//skullfire sword
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:skullfire_sword>, [[null, null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>], [null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>], [null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null], [null, <ore:bone>, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null], [null, null, <ore:bone>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null, null], [null, null, <ore:logWood>, <ore:bone>, null, null, null, null, null], [null, <ore:logWood>, null, null, <ore:bone>, null, null, null, null], [<ore:netherStar>, null, null, null, null, null, null, null, null]]);
//nature's ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_axe>, [[null, null, null, <ore:ingotInfinity>, null, null, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);
//infinity catalyst
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:5>, [[null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <avaritia:cosmic_meatballs>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:ultimate_stew>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <mysticalagradditions:stuff:69>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);
