#packmode beast
#modloaded extendedcrafting avaritia

//neutronium compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
//cosmic meatballs
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:cosmic_meatballs> * 3, [<avaritia:resource:2>, <minecraft:beef>, <minecraft:beef>, <abyssalcraft:antibeef>, <abyssalcraft:antibeef>, <minecraft:chicken>, <minecraft:chicken>, <abyssalcraft:antichicken>, <abyssalcraft:antichicken>, <minecraft:porkchop>, <minecraft:porkchop>, <abyssalcraft:antipork>, <abyssalcraft:antipork>, <minecraft:rabbit>, <minecraft:rabbit>, <minecraft:mutton>, <minecraft:mutton>, <natura:edibles:0>, <natura:edibles:0>, <ore:listAllfishraw>, <ore:listAllfishraw>, <twilightforest:raw_meef>, <twilightforest:raw_meef>, <twilightforest:raw_venison>, <twilightforest:raw_venison>, <netherex:ghast_meat_raw>, <netherex:ghast_meat_raw>]);
//ultimate stew
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);
mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:ultimate_stew> * 3, [<avaritia:resource:3>, <ore:toolPot>, <ore:foodStock>, <ore:foodChickendinner>, <ore:cropRice>, <ore:cropBean>, <ore:foodSpicygreens>, <ore:cropTomato>, <ore:cropPotato>]);
//endest pearl
mods.avaritia.ExtremeCrafting.remove(<avaritia:endest_pearl>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:endest_pearl>, [[null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null]]);
//planet eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_shovel>, [[null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null], [<ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null, null]]);
//World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_pickaxe>, [[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotInfinity>, null, null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);
//hoe of green earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_hoe>, [[null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null]]);
//longbow of the heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_bow>, [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:blockCrystalMatrix>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null]]);
//skullfire sword
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:skullfire_sword>, [[null, null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>], [null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>], [null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null], [null, <ore:bone>, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null], [null, null, <ore:bone>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null, null], [null, null, <ore:logWood>, <ore:bone>, null, null, null, null, null], [null, <ore:logWood>, null, null, <ore:bone>, null, null, null, null], [<ore:netherStar>, null, null, null, null, null, null, null, null]]);
//nature's ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_axe>, [[null, null, null, <ore:ingotInfinity>, null, null, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);
//infinity catalyst
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:5>, [[null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <avaritia:cosmic_meatballs>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:ultimate_stew>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <mysticalagradditions:stuff:69>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);
//crystal matrix ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:1>, [[<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <extraplanets:tier5_items:12>, <avaritia:resource>, <extraplanets:tier5_items:12>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [<projectex:matter:5>, <extraplanets:tier5_items:12>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <extraplanets:tier5_items:12>, <projectex:matter:5>], [<ore:runeSummerB>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <draconicevolution:draconic_core>, <actuallyadditions:item_crystal_empowered:5>, <draconicevolution:draconic_core>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:runeSummerB>], [<projectex:matter:5>, <extraplanets:tier5_items:12>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <extraplanets:tier5_items:12>, <projectex:matter:5>], [<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <extraplanets:tier5_items:12>, <avaritia:resource>, <extraplanets:tier5_items:12>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);
//neutron collector
recipes.remove(<avaritia:neutron_collector>);
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:neutron_collector>, [
[<ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockCertusQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>],
[<ore:blockIron>, <ore:ingotUltimate>, <draconicevolution:awakened_core>, <extrautils2:terraformer:5>, <extraplanets:tier10_items:4>, <extrautils2:terraformer:5>, <draconicevolution:awakened_core>, <ore:ingotUltimate>, <ore:blockIron>],
[<ore:blockIron>, <draconicevolution:awakened_core>, <extrautils2:terraformer:5>, <ore:ingotDemonicMetal>, <ore:blockElectrotineAlloy>, <ore:ingotDemonicMetal>, <extrautils2:terraformer:5>, <draconicevolution:awakened_core>, <ore:blockIron>],
[<ore:blockIron>, <extrautils2:terraformer:5>, <ore:ingotDemonicMetal>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <ore:ingotDemonicMetal>, <extrautils2:terraformer:5>, <ore:blockIron>],
[<ore:blockQuartz>, <extraplanets:tier10_items:4>, <ore:blockElectrotineAlloy>, <abyssalcraft:crystalcluster:11>, <ore:blockElectrotineAlloy>, <abyssalcraft:crystalcluster:11>, <ore:blockElectrotineAlloy>, <extraplanets:tier10_items:4>, <ore:blockQuartz>],
[<ore:blockIron>, <tp:lava_infused_stone>, <ore:ingotDemonicMetal>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <ore:ingotDemonicMetal>, <tp:lava_infused_stone>, <ore:blockIron>],
[<ore:blockIron>, <draconicevolution:awakened_core>, <tp:lava_infused_stone>, <ore:ingotDemonicMetal>, <ore:blockElectrotineAlloy>, <ore:ingotDemonicMetal>, <tp:lava_infused_stone>, <draconicevolution:awakened_core>, <ore:blockIron>],
[<ore:blockIron>, <ore:ingotUltimate>, <draconicevolution:awakened_core>, <tp:lava_infused_stone>, <extraplanets:tier10_items:4>, <tp:lava_infused_stone>, <draconicevolution:awakened_core>, <ore:ingotUltimate>, <ore:blockIron>],
[<ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>]]);
//infinity ingot
recipes.remove(<avaritia:resource:6>);
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:6>, [
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>],
[<ore:ingotUltimate>, <avaritia:resource:5>, <abyssalcraft:crystalcluster:14>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <abyssalcraft:crystalcluster:14>, <avaritia:resource:5>, <ore:ingotUltimate>],
[<extraplanets:wafer:5>, <projectex:matter:10>, <avaritia:resource:5>, <avaritia:resource:5>, <projectex:matter:10>, <avaritia:resource:5>, <avaritia:resource:5>, <projectex:matter:10>, <extraplanets:wafer:5>],
[<ore:ingotUltimate>, <avaritia:resource:5>, <abyssalcraft:crystalcluster:14>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <abyssalcraft:crystalcluster:14>, <avaritia:resource:5>, <ore:ingotUltimate>],
[<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);
//sword of the cosmos
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_sword>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_sword>, [[null, null, null, null, null, null, null, <ore:ingotInfinity>, <draconicevolution:draconic_staff_of_power>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, <ore:ingotCrystalMatrix>, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, null, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotCrystalMatrix>, null, null, null, null], [<avaritia:resource:5>, null, null, null, null, null, null, null, null]]);
