#modloaded extendedcrafting jaopca nuclearcraft

import mods.extendedcrafting.CombinationCrafting as CC;

// Singularity - Boron
CC.addRecipe(<jaopca:item_singularityboron>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>, <extendedcrafting:singularity_custom:77>]);
// Singularity - Palladium
CC.addRecipe(<jaopca:item_singularitypalladium>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>, <extendedcrafting:singularity_custom:128>]);
// Singularity - Thorium
CC.addRecipe(<jaopca:item_singularitythorium>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>, <extendedcrafting:singularity_custom:140>]);
// Singularity - Titanium
CC.addRecipe(<jaopca:item_singularitytitanium>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>, <extendedcrafting:singularity_custom:143>]);
// Singularity - Tungsten
CC.addRecipe(<jaopca:item_singularitytungsten>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>, <extendedcrafting:singularity_custom:144>]);
// Singularity - Sulfur / Sulphur
CC.addRecipe(<jaopca:item_singularitysulfur>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>, <extendedcrafting:singularity_custom:355>]);
// Singularity - Uranium
CC.addRecipe(<jaopca:item_singularityuranium>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>, <extendedcrafting:singularity_custom:145>]);
// Singularity - Yellorium
CC.addRecipe(<jaopca:item_singularityyellorium>, 5000000, <extendedcrafting:material:13>, [<extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>, <extendedcrafting:singularity_custom:147>]);
