#packmode mythic beast
#modloaded extendedcrafting mysticalagriculture mysticalagradditions darkutils botania avaritia

import mods.extendedcrafting.TableCrafting.addShaped as TC;

recipes.remove(<mysticalagradditions:nether_star_seeds>);

//Tier 6 -	Extended Crafting - 9x9
TC(0, <mysticalagradditions:nether_star_seeds>, [[<ore:essenceInsanium>, <ore:essenceInsanium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <botania:pinkinator>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceInsanium>, <ore:essenceInsanium>], [<ore:essenceInsanium>, <ore:essenceInsanium>, <mysticalagriculture:witherproof_glass>, <mysticalagriculture:witherproof_glass>, <enderio:block_reinforced_obsidian>, <mysticalagriculture:witherproof_glass>, <mysticalagriculture:witherproof_glass>, <ore:essenceInsanium>, <ore:essenceInsanium>], [<ore:ingotEnderEnhanced>, <ore:blockWither>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:blockWither>, <ore:ingotEnderEnhanced>], [<ore:ingotEnderEnhanced>, <ore:blockWither>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <mysticalagradditions:stuff:1>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <ore:blockWither>, <ore:ingotEnderEnhanced>], [<botania:pinkinator>, <enderio:block_reinforced_obsidian>, <ore:ingotCosmicNeutronium>, <mysticalagradditions:stuff:1>, <mysticalagradditions:insanium:1>, <mysticalagradditions:stuff:1>, <ore:ingotCosmicNeutronium>, <enderio:block_reinforced_obsidian>, <botania:pinkinator>], [<ore:ingotEnderEnhanced>, <ore:blockWither>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <mysticalagradditions:stuff:1>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <ore:blockWither>, <ore:ingotEnderEnhanced>], [<ore:ingotEnderEnhanced>, <ore:blockWither>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:blockWither>, <ore:ingotEnderEnhanced>], [<ore:essenceInsanium>, <ore:essenceInsanium>, <mysticalagriculture:witherproof_block>, <mysticalagriculture:witherproof_block>, <enderio:block_reinforced_obsidian>, <mysticalagriculture:witherproof_block>, <mysticalagriculture:witherproof_block>, <ore:essenceInsanium>, <ore:essenceInsanium>], [<ore:essenceInsanium>, <ore:essenceInsanium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <botania:pinkinator>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceInsanium>, <ore:essenceInsanium>]]);
