#packmode mythic beast
#modloaded botania mysticalagriculture jaopca nuclearcraft

import mods.botania.RuneAltar.addRecipe as bot;

recipes.remove(<jaopca:item_mysticalseedsboronnitride>);
recipes.remove(<jaopca:item_mysticalseedsferroboron>);
recipes.remove(<jaopca:item_mysticalseedshardcarbon>);
recipes.remove(<jaopca:item_mysticalseedslithiummanganesedioxide>);
recipes.remove(<jaopca:item_mysticalseedsmanganeseoxide>);
recipes.remove(<jaopca:item_mysticalseedssiliconcarbide>);

// Tier 3,1

bot(<jaopca:item_mysticalseedsboronnitride>, [<ore:blockBoronNitride>, <ore:blockBoronNitride>, <ore:blockBoronNitride>, <ore:blockBoronNitride>, <mysticalagriculture:boron_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "boron_plant", agri_growth: 10 as byte}), <forge:bucketfilled>.withTag({FluidName: "ammonia",Amount:1000}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 8000);
bot(<jaopca:item_mysticalseedsmanganeseoxide>, [<ore:blockManganeseOxide>, <ore:blockManganeseOxide>, <ore:blockManganeseOxide>, <ore:blockManganeseOxide>, <jaopca:item_mysticalseedsmanganese>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "manganese_mystical_plant", agri_growth: 10 as byte}), <forge:bucketfilled>.withTag({FluidName: "oxygen",Amount:1000}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 8000);

/*
//NC-Unerhaul Recipes
recipes.remove(<jaopca:item_mysticalseedsthoriumoxide>);
recipes.remove(<jaopca:item_mysticalseedsuraniumoxide>);
bot(<jaopca:item_mysticalseedsthoriumoxide>, [<ore:blockThoriumOxide>, <ore:blockThoriumOxide>, <ore:blockThoriumOxide>, <ore:blockThoriumOxide>, <mysticalagriculture:thorium_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "thorium_plant", agri_growth: 10 as byte}), <forge:bucketfilled>.withTag({FluidName: "oxygen",Amount:1000}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 8000);
bot(<jaopca:item_mysticalseedsuraniumoxide>, [<ore:blockUraniumOxide>, <ore:blockUraniumOxide>, <ore:blockUraniumOxide>, <ore:blockUraniumOxide>, <mysticalagriculture:uranium_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "uranium_plant", agri_growth: 10 as byte}), <forge:bucketfilled>.withTag({FluidName: "oxygen",Amount:1000}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 8000);
*/

// Tier 3,2

bot(<jaopca:item_mysticalseedsferroboron>, [<ore:blockFerroboron>, <ore:blockFerroboron>, <ore:blockFerroboron>, <ore:blockFerroboron>, <mysticalagriculture:steel_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "steel_plant", agri_growth: 10 as byte}), <mysticalagriculture:boron_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "boron_plant", agri_growth: 10 as byte}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <mysticalagriculture:crafting:19>], 8000);
bot(<jaopca:item_mysticalseedsferroboron>, [<ore:blockFerroboron>, <ore:blockFerroboron>, <ore:blockFerroboron>, <ore:blockFerroboron>, <mysticalagriculture:iron_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "iron_plant", agri_growth: 10 as byte}), <mysticalagriculture:coal_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "coal_plant", agri_growth: 10 as byte}), <mysticalagriculture:boron_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "boron_plant", agri_growth: 10 as byte}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <mysticalagriculture:crafting:19>], 8000);

bot(<jaopca:item_mysticalseedshardcarbon>, [<ore:blockHardCarbon>, <ore:blockHardCarbon>, <ore:blockHardCarbon>, <ore:blockHardCarbon>, <mysticalagriculture:graphite_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "graphite_plant", agri_growth: 10 as byte}), <mysticalagriculture:diamond_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "diamond_plant", agri_growth: 10 as byte}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <mysticalagriculture:crafting:19>], 8000);
bot(<jaopca:item_mysticalseedslithiummanganesedioxide>, [<ore:blockLithiumManganeseDioxide>, <ore:blockLithiumManganeseDioxide>, <ore:blockLithiumManganeseDioxide>, <ore:blockLithiumManganeseDioxide>, <mysticalagriculture:lithium_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "lithium_plant", agri_growth: 10 as byte}), <jaopca:item_mysticalseedsmanganesedioxide>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "manganese_dioxide_mystical_plant", agri_growth: 10 as byte}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <mysticalagriculture:crafting:19>], 8000);
bot(<jaopca:item_mysticalseedssiliconcarbide>, [<ore:blockSiliconCarbide>, <ore:blockSiliconCarbide>, <ore:blockSiliconCarbide>, <ore:blockSiliconCarbide>, <mysticalagriculture:silicon_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "silicon_plant", agri_growth: 10 as byte}), <mysticalagriculture:graphite_seeds>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "graphite_plant", agri_growth: 10 as byte}), <ore:elvenDragonstone>, <ore:elvenPixieDust>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <ore:ingotIntermedium>, <mysticalagriculture:crafting:19>], 8000);
