#packmode beast
#modloaded astralsorcery simplyjetpacks mysticalagriculture jaopca nuclearcraft

import mods.extendedcrafting.TableCrafting.addShaped as TC;

recipes.remove(<jaopca:item_mysticalseedsberyllium>);
recipes.remove(<jaopca:item_mysticalseedscarobbiite>);
recipes.remove(<jaopca:item_mysticalseedsfluorite>);
recipes.remove(<jaopca:item_mysticalseedsmanganesedioxide>);
recipes.remove(<jaopca:item_mysticalseedsrhodochrosite>);
recipes.remove(<jaopca:item_mysticalseedsvilliaumite>);
recipes.remove(<jaopca:item_mysticalseedszirconium>);

// Tier 5,1

TC(0, <jaopca:item_mysticalseedsberyllium>, [[<ore:itemInfinityGoop>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:itemInfinityGoop>], [<ore:blockBeryllium>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockBeryllium>], [<ore:blockBeryllium>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockBeryllium>], [<ore:blockBeryllium>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockBeryllium>], [<ore:blockBeryllium>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockBeryllium>], [<ore:blockBeryllium>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockBeryllium>], [<ore:itemInfinityGoop>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:blockBeryllium>, <ore:itemInfinityGoop>]]);
TC(0, <jaopca:item_mysticalseedscarobbiite>, [[<ore:itemInfinityGoop>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:itemInfinityGoop>], [<ore:blockCarobbiite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockCarobbiite>], [<ore:blockCarobbiite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockCarobbiite>], [<ore:blockCarobbiite>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockCarobbiite>], [<ore:blockCarobbiite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockCarobbiite>], [<ore:blockCarobbiite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockCarobbiite>], [<ore:itemInfinityGoop>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:blockCarobbiite>, <ore:itemInfinityGoop>]]);
TC(0, <jaopca:item_mysticalseedsfluorite>, [[<ore:itemInfinityGoop>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:itemInfinityGoop>], [<ore:blockFluorite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockFluorite>], [<ore:blockFluorite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockFluorite>], [<ore:blockFluorite>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockFluorite>], [<ore:blockFluorite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockFluorite>], [<ore:blockFluorite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockFluorite>], [<ore:itemInfinityGoop>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:blockFluorite>, <ore:itemInfinityGoop>]]);
TC(0, <jaopca:item_mysticalseedsrhodochrosite>, [[<ore:itemInfinityGoop>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:itemInfinityGoop>], [<ore:blockRhodochrosite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockRhodochrosite>], [<ore:blockRhodochrosite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockRhodochrosite>], [<ore:blockRhodochrosite>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockRhodochrosite>], [<ore:blockRhodochrosite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockRhodochrosite>], [<ore:blockRhodochrosite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockRhodochrosite>], [<ore:itemInfinityGoop>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:blockRhodochrosite>, <ore:itemInfinityGoop>]]);
TC(0, <jaopca:item_mysticalseedsvilliaumite>, [[<ore:itemInfinityGoop>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:itemInfinityGoop>], [<ore:blockVilliaumite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockVilliaumite>], [<ore:blockVilliaumite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockVilliaumite>], [<ore:blockVilliaumite>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockVilliaumite>], [<ore:blockVilliaumite>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockVilliaumite>], [<ore:blockVilliaumite>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockVilliaumite>], [<ore:itemInfinityGoop>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:blockVilliaumite>, <ore:itemInfinityGoop>]]);
TC(0, <jaopca:item_mysticalseedszirconium>, [[<ore:itemInfinityGoop>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:itemInfinityGoop>], [<ore:blockZirconium>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockZirconium>], [<ore:blockZirconium>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockZirconium>], [<ore:blockZirconium>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockZirconium>], [<ore:blockZirconium>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockZirconium>], [<ore:blockZirconium>, <ore:essenceSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:essenceSupremium>, <ore:blockZirconium>], [<ore:itemInfinityGoop>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:blockZirconium>, <ore:itemInfinityGoop>]]);

// Tier 5,2

TC(0, <jaopca:item_mysticalseedsmanganesedioxide>, [[<jaopca:item_mysticalseedsmanganeseoxide>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "manganese_oxide_mystical_plant", agri_growth: 10 as byte}), <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <jaopca:item_mysticalseedsmanganese>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "manganese_mystical_plant", agri_growth: 10 as byte})], [<ore:blockManganeseDioxide>, <ore:ingotSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotSupremium>, <ore:blockManganeseDioxide>], [<ore:blockManganeseDioxide>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockManganeseDioxide>], [<ore:blockManganeseDioxide>, <ore:ingotEnderEnhanced>, <simplyjetpacks:metaitemmods:12>, <mysticalagriculture:crafting:21>, <simplyjetpacks:metaitemmods:12>, <ore:ingotEnderEnhanced>, <ore:blockManganeseDioxide>], [<ore:blockManganeseDioxide>, <ore:ingotEnderEnhanced>, <ore:coinBlackIron>, <simplyjetpacks:metaitemmods:12>, <ore:coinBlackIron>, <ore:ingotEnderEnhanced>, <ore:blockManganeseDioxide>], [<ore:blockManganeseDioxide>, <ore:ingotSupremium>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotEnderEnhanced>, <ore:ingotSupremium>, <ore:blockManganeseDioxide>], [<forge:bucketfilled>.withTag({FluidName: "oxygen",Amount:1000}), <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <ore:blockManganeseDioxide>, <forge:bucketfilled>.withTag({FluidName: "oxygen",Amount:1000})]]);
