#packmode beast
#modloaded extendedcrafting

//neutronium compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);

//neutronium solar panel
mods.avaritia.ExtremeCrafting.remove(<solarflux:solar_panel_neutronium>);

mods.extendedcrafting.TableCrafting.addShaped(0, <solarflux:solar_panel_neutronium>, [[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotUltimate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, <avaritia:resource:3>, null, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<thermalsolars:blockenderpanel>, <solarflux:solar_panel_chaotic>, <avaritia:resource:3>, <avaritia:resource:2>, <avaritia:resource:5>, <avaritia:resource:2>, <avaritia:resource:3>, <solarflux:solar_panel_chaotic>, <thermalsolars:blockenderpanel>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, <avaritia:resource:3>, null, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotUltimate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

// Eternal Singularity
mods.extendedcrafting.TableCrafting.addShaped(0, <eternalsingularity:eternal_singularity>,
[[<jaopca:item_singularityabyssalnite>, <jaopca:item_singularityaluminium>, <jaopca:item_singularityadamantine>, <jaopca:item_singularityaquamarine>, <jaopca:item_singularityardite>, <jaopca:item_singularityastralstarmetal>, <extendedcrafting:singularity_custom:150>, <extendedcrafting:singularity_custom:151>, <extendedcrafting:singularity_custom:152>],
[<jaopca:item_singularityboron>, <extendedcrafting:singularity_custom:153>, <jaopca:item_singularitycarbon>, <jaopca:item_singularitycoal>, <extendedcrafting:singularity_custom:154>, <avaritia:singularity:5>, <jaopca:item_singularityliquifiedcoralium>, <jaopca:item_singularitycrystal>, <extendedcrafting:singularity_custom:155>],
[<extendedcrafting:singularity_custom:156>, <extendedcrafting:singularity_custom:157>, <extendedcrafting:singularity_custom:158>, <extendedcrafting:singularity_custom:159>, <extendedcrafting:singularity_custom:160>, <jaopca:item_singularitydimensionalshard>, <jaopca:item_singularitydraconium>, <extendedcrafting:singularity_custom:161>, <extendedcrafting:singularity_custom:162>],
[<extendedcrafting:singularity_custom:163>, <extendedcrafting:singularity_custom:164>, <avaritia:singularity:11>, <extendedcrafting:singularity_custom:165>, <extendedcrafting:singularity_custom:166>, <extendedcrafting:singularity_custom:167>, <extendedcrafting:singularity_custom:168>, <extendedcrafting:singularity_custom:169>, <extendedcrafting:singularity_custom:170>],
[<avaritia:singularity:12>, <extendedcrafting:singularity_custom:171>, <extendedcrafting:singularity_custom:172>, <avaritia:singularity:1>, <extendedcrafting:singularity_custom:173>, <extendedcrafting:singularity_custom:174>, <avaritia:singularity:14>, <avaritia:singularity:0>, <extendedcrafting:singularity_custom:175>],
[<jaopca:item_singularityjade>, <extendedcrafting:singularity_custom:176>, <extendedcrafting:singularity_custom:177>, <avaritia:singularity:7>, <jaopca:item_singularitylithium>, <extendedcrafting:singularity_custom:178>, <extendedcrafting:singularity_custom:179>, <jaopca:item_singularitylunar>, <jaopca:item_singularitymagnesium>],
[<extendedcrafting:singularity_custom:180>, <jaopca:item_singularitymithril>, <jaopca:item_singularityknightslime>, <avaritia:singularity:4>, <extendedcrafting:singularity_custom:181>, <avaritia:singularity:9>, <jaopca:item_singularitypalladium>, <avaritia:singularity:13>, <jaopca:item_singularityknightslime>],
[<avaritia:singularity:3>, <extendedcrafting:singularity_custom:182>, <extendedcrafting:singularity_custom:183>, <avaritia:singularity:8>, <extendedcrafting:singularity_custom:184>, <extendedcrafting:singularity_custom:185>, <extendedcrafting:singularity_custom:186>, <extendedcrafting:singularity_custom:187>, <extendedcrafting:singularity_custom:188>],
[<jaopca:item_singularitythorium>, <avaritia:singularity:6>, <jaopca:item_singularitytitanium>, <jaopca:item_singularitytungsten>, <jaopca:item_singularityuranium>, <extendedcrafting:singularity_custom:189>, <jaopca:item_singularityyellorium>, <jaopca:item_singularityzinc>, <extendedcrafting:singularity_custom:190>]]);

//Genesis Spectre Charger

mods.extendedcrafting.TableCrafting.addShaped(0, <randomthings:spectrecharger:3> * 16, [
[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <randomthings:spectrecharger:2>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null],
[null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <draconicevolution:draconium_capacitor:1>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <enderio:item_endergy_conduit:11>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <thermaldynamics:duct_0:5>, <ore:ingotInfinity>, <thermaldynamics:duct_0:5>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<randomthings:spectrecharger:2>, <overloaded:infinite_capacitor>, <enderio:item_endergy_conduit:11>, <ore:ingotInfinity>, <solarflux:solar_panel_infinity>, <ore:ingotInfinity>, <enderio:item_endergy_conduit:11>, <overloaded:infinite_capacitor>, <randomthings:spectrecharger:2>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <thermaldynamics:duct_0:5>, <ore:ingotInfinity>, <thermaldynamics:duct_0:5>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <enderio:item_endergy_conduit:11>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <magneticraft:infinite_energy:0>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null],
[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <randomthings:spectrecharger:2>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

//Genesis Spectre Coil

mods.extendedcrafting.TableCrafting.addShaped(0, <randomthings:spectrecoil_genesis> * 16, [
[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <randomthings:spectrecoil_ender>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null],
[null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <draconicevolution:draconium_capacitor:1>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <enderio:item_endergy_conduit:11>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <thermaldynamics:duct_0:5>, <ore:ingotInfinity>, <thermaldynamics:duct_0:5>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<randomthings:spectrecoil_ender>, <overloaded:infinite_capacitor>, <enderio:item_endergy_conduit:11>, <ore:ingotInfinity>, <solarflux:solar_panel_infinity>, <ore:ingotInfinity>, <enderio:item_endergy_conduit:11>, <overloaded:infinite_capacitor>, <randomthings:spectrecoil_ender>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <thermaldynamics:duct_0:5>, <ore:ingotInfinity>, <thermaldynamics:duct_0:5>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <enderio:item_endergy_conduit:11>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>],
[null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <magneticraft:infinite_energy:0>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null],
[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <randomthings:spectrecoil_ender>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

// Nitronic Singularity
mods.extendedcrafting.TableCrafting.addShaped(0, <eternalsingularity:combined_singularity>, [
[<extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_custom:216>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_custom:277>, <extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity_ultimate>],
[<extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>]]);

//infinity solar panel
mods.avaritia.ExtremeCrafting.remove(<solarflux:solar_panel_infinity>);

mods.extendedcrafting.TableCrafting.addShaped(0, <solarflux:solar_panel_infinity> * 3, [[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <thermalsolars:blocksolarpanel103>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <ore:nuggetCosmicNeutronium>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <ore:ingotInfinity>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<thermalsolars:blockenderpanel>, <thermalsolars:blocksolarpanel103>, <ore:nuggetCosmicNeutronium>, <ore:ingotInfinity>, <solarflux:solar_panel_neutronium>, <ore:ingotInfinity>, <ore:nuggetCosmicNeutronium>, <thermalsolars:blocksolarpanel103>, <thermalsolars:blockenderpanel>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <ore:ingotInfinity>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <ore:nuggetCosmicNeutronium>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <thermalsolars:blocksolarpanel103>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

//I'm a Potato!
mods.avaritia.ExtremeCrafting.remove(<avaritiatweaks:infinitato>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritiatweaks:infinitato>, [[<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <avaritia:resource:5>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>]]);

//cosmic meatballs
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);

mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:cosmic_meatballs> * 3, [<avaritia:resource:2>, <minecraft:beef>, <minecraft:beef>, <abyssalcraft:antibeef>, <abyssalcraft:antibeef>, <minecraft:chicken>, <minecraft:chicken>, <abyssalcraft:antichicken>, <abyssalcraft:antichicken>, <minecraft:porkchop>, <minecraft:porkchop>, <abyssalcraft:antipork>, <abyssalcraft:antipork>, <minecraft:rabbit>, <minecraft:rabbit>, <minecraft:mutton>, <minecraft:mutton>, <natura:edibles:0>, <natura:edibles:0>, <ore:listAllfishraw>, <ore:listAllfishraw>, <twilightforest:raw_meef>, <twilightforest:raw_meef>, <twilightforest:raw_venison>, <twilightforest:raw_venison>, <netherex:ghast_meat_raw>, <netherex:ghast_meat_raw>]);

//ultimate stew
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);

mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:ultimate_stew> * 3, [<avaritia:resource:3>, <ore:toolPot>, <ore:foodStock>, <ore:foodChickendinner>, <ore:cropRice>, <ore:cropBean>, <ore:foodSpicygreens>, <ore:cropTomato>, <ore:cropPotato>]);

//endest pearl
mods.avaritia.ExtremeCrafting.remove(<avaritia:endest_pearl>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:endest_pearl>, [[null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:netherStar>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [<ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:ingotCosmicNeutronium>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>], [null, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, null], [null, <ore:endstone>, <ore:endstone>, <ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>, <ore:endstone>, <ore:endstone>, null], [null, null, null, <ore:endstone>, <ore:endstone>, <ore:endstone>, null, null, null]]);

//planet eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_shovel>, [[null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null], [<ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null, null]]);

//World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_pickaxe>, [[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotInfinity>, null, null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//hoe of green earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_hoe>, [[null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null]]);

//longbow of the heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_bow>, [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:blockCrystalMatrix>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null]]);

//asgardandelion
mods.avaritia.ExtremeCrafting.remove(<botania:specialflower:0>.withTag({type:"asgardandelion"}));

mods.extendedcrafting.TableCrafting.addShaped(4, <botania:specialflower:0>.withTag({type:"asgardandelion"}), [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, <avaritia:resource:3>, <avaritia:resource:3>, null, <ore:ingotCosmicNeutronium>, null, <avaritia:resource:3>, <avaritia:resource:3>, null], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <ore:ingotCosmicNeutronium>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>], [null, <avaritia:resource:3>, <avaritia:resource:3>, null, <ore:ingotCosmicNeutronium>, null, <avaritia:resource:3>, <avaritia:resource:3>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//skullfire sword
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:skullfire_sword>, [[null, null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>], [null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>], [null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null], [null, <ore:bone>, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null], [null, null, <ore:bone>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null, null], [null, null, <ore:logWood>, <ore:bone>, null, null, null, null, null], [null, <ore:logWood>, null, null, <ore:bone>, null, null, null, null], [<ore:netherStar>, null, null, null, null, null, null, null, null]]);

//nature's ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_axe>, [[null, null, null, <ore:ingotInfinity>, null, null, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);

//infinity catalyst
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:5>, [[null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <avaritia:cosmic_meatballs>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:ultimate_stew>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <mysticalagradditions:stuff:69>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//enhancement crystal
mods.avaritia.ExtremeCrafting.remove(<avaritiatweaks:enhancement_crystal>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritiatweaks:enhancement_crystal>, [[null, null, null, null, <avaritia:resource:4>, null, null, null, null], [null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null], [null, null, null, null, <avaritia:resource:4>, null, null, null, null]]);

//projecte
//philosphers stone
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:item.pe_philosophers_stone>.withEmptyTag(), [[null, <ore:treeLeaves>, <ore:crystalRedstone>, <ore:ingotSupremium>, <mysticalagradditions:stuff:69>, <ore:ingotSupremium>, <ore:crystalRedstone>, <ore:treeLeaves>, null], [<mysticalagradditions:insanium:4>, <erebus:materials:64>, <ore:ingotThorium>, <ore:plasticRed>, <botania:blackholetalisman>, <ore:plasticRed>, <ore:ingotThorium>, <erebus:materials:64>, <mysticalagradditions:insanium:4>], [<ore:ingotSupremium>, <twilightforest:fiery_tears>, <enderio:item_capacitor_totemic>, <abyssalcraft:oc>, <netherex:ghast_queen_tear>, <abyssalcraft:oc>, <enderio:item_capacitor_totemic>, <twilightforest:fiery_tears>, <ore:ingotSupremium>], [<ore:crystalRedstone>, <ore:plasticRed>, <ore:fuelHECf251Oxide>, <appliedenergistics2:material:6>, <draconicevolution:wyvern_core>, <appliedenergistics2:material:6>, <ore:fuelHECf251Oxide>, <ore:plasticRed>, <ore:crystalRedstone>], [<mysticalagradditions:stuff:69>, <ore:gemRedGem>, <netherex:ghast_queen_tear>, <embers:ember_cluster>, <lordcraft:trans_researchb>, <embers:ember_cluster>, <netherex:ghast_queen_tear>, <ore:gemRedGem>, <mysticalagradditions:stuff:69>], [<ore:crystalRedstone>, <ore:plasticRed>, <ore:fuelHECf251Oxide>, <appliedenergistics2:material:6>, <draconicevolution:wyvern_core>, <appliedenergistics2:material:6>, <ore:fuelHECf251Oxide>, <ore:plasticRed>, <ore:crystalRedstone>], [<ore:ingotSupremium>, <twilightforest:fiery_tears>, <enderio:item_capacitor_totemic>, <abyssalcraft:oc>, <netherex:ghast_queen_tear>, <abyssalcraft:oc>, <enderio:item_capacitor_totemic>, <twilightforest:fiery_tears>, <ore:ingotSupremium>], [<mysticalagradditions:insanium:4>, <erebus:materials:64>, <ore:ingotThorium>, <ore:plasticRed>, <botania:blackholetalisman>, <ore:plasticRed>, <ore:ingotThorium>, <erebus:materials:64>, <mysticalagradditions:insanium:4>], [null, <ore:treeLeaves>, <ore:crystalRedstone>, <ore:ingotSupremium>, <mysticalagradditions:stuff:69>, <ore:ingotSupremium>, <ore:crystalRedstone>, <ore:treeLeaves>, null]]);

//staff of power
mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:draconic_staff_of_power>, [[<mysticalagriculture:supremium_sword>, <randomthings:spectresword>, <lordcraft:sword_light>, <draconicevolution:awakened_core>, <draconicevolution:draconic_sword>, <draconicevolution:awakened_core>, <lordcraft:sword_dark>, <redstonearsenal:tool.sword_flux>, <twilightforest:fiery_sword>], [<lordcraft:pick_water>, <enderio:item_stellar_alloy_pickaxe>, <draconicevolution:draconic_pick>, <ore:ingotDraconiumAwakened>, <draconicevolution:draconic_energy_core>, <ore:ingotDraconiumAwakened>, <draconicevolution:draconic_axe>, <enderio:item_stellar_alloy_axe>, <lordcraft:axe_earth>], [<lordcraft:spade_fire>, <draconicevolution:draconic_shovel>, null, <draconicevolution:awakened_core>, <ore:ingotDraconiumAwakened>, <draconicevolution:awakened_core>, null, <ore:toolHoe>, <lordcraft:hoe_air>], [<projecte:item.pe_rm_katar>, null, null, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, null, null, <projecte:item.pe_rm_morning_star>], [null, null, <armorplus:infused_lava_battle_axe>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <armorplus:guardian_battle_axe>, null, null], [null, null, <armorplus:super_star_battle_axe>, <draconicevolution:awakened_core>, <ore:ingotDraconiumAwakened>, <draconicevolution:awakened_core>, <armorplus:ender_dragon_battle_axe>, null, null], [null, null, null, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, <ore:ingotDraconiumAwakened>, null, null, null], [null, null, null, <ore:ingotDraconiumAwakened>, <draconicevolution:draconic_energy_core>, <ore:ingotDraconiumAwakened>, null, null, null], [null, null, null, <ore:ingotDraconiumAwakened>, <ore:blockCrystalMatrix>, <ore:ingotDraconiumAwakened>, null, null, null]]);

//transmutation table
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:transmutation_table>, [[<projecte:matter_block>, <projecte:matter_block>, <ore:itemCompressedObsidian>, <ore:compressed1xDust>, <ore:blockEndSteel>, <ore:compressed1xDust>, <ore:itemCompressedObsidian>, <projecte:matter_block>, <projecte:matter_block>], [<projecte:matter_block>, <projecte:matter_block>, <ore:blockKelline>, <enderio:item_capacitor_stellar>, <ore:ingotInsanium>, <enderio:item_capacitor_stellar>, <ore:blockKelline>, <projecte:matter_block>, <projecte:matter_block>], [<ore:itemCompressedObsidian>, <ore:blockKelline>, <enderio:item_capacitor_stellar>, <projectex:matter>, <ore:ingotInsanium>, <projectex:matter:1>, <enderio:item_capacitor_stellar>, <ore:blockKelline>, <ore:itemCompressedObsidian>], [<ore:compressed1xDust>, <enderio:item_capacitor_stellar>, <projectex:matter:1>, <ore:ingotSupremium>, <projectex:matter:2>, <ore:ingotSupremium>, <projectex:matter>, <enderio:item_capacitor_stellar>, <ore:compressed1xDust>], [<ore:blockEndSteel>, <ore:ingotInsanium>, <ore:ingotInsanium>, <projectex:matter:2>, <projecte:item.pe_philosophers_stone>.noReturn(), <projectex:matter:2>, <ore:ingotInsanium>, <ore:ingotInsanium>, <ore:blockEndSteel>], [<ore:compressed1xDust>, <enderio:item_capacitor_stellar>, <projectex:matter>, <ore:ingotSupremium>, <projectex:matter:2>, <ore:ingotSupremium>, <projectex:matter:1>, <enderio:item_capacitor_stellar>, <ore:compressed1xDust>], [<ore:itemCompressedObsidian>, <ore:blockKelline>, <enderio:item_capacitor_stellar>, <projectex:matter:1>, <ore:ingotInsanium>, <projectex:matter>, <enderio:item_capacitor_stellar>, <ore:blockKelline>, <ore:itemCompressedObsidian>], [<projecte:matter_block>, <projecte:matter_block>, <ore:blockKelline>, <enderio:item_capacitor_stellar>, <ore:ingotInsanium>, <enderio:item_capacitor_stellar>, <ore:blockKelline>, <projecte:matter_block>, <projecte:matter_block>], [<projecte:matter_block>, <projecte:matter_block>, <ore:itemCompressedObsidian>, <ore:compressed1xDust>, <ore:blockEndSteel>, <ore:compressed1xDust>, <ore:itemCompressedObsidian>, <projecte:matter_block>, <projecte:matter_block>]]);

//transmutation tablet
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:item.pe_transmutation_tablet>, [[<projecte:matter_block:1>, <projecte:matter_block:1>, <ore:oc:craftingUpgrade>, <projectex:matter:3>, <ore:oc:craftingUpgrade>, <projectex:matter:4>, <ore:oc:craftingUpgrade>, <projecte:matter_block:1>, <projecte:matter_block:1>], [<projecte:matter_block:1>, <projecte:matter_block:1>, <extraplanets:tier5_items:4>, <extraplanets:tier6_items:4>, <ore:gemWhiteGem>, <extraplanets:tier6_items:4>, <extraplanets:tier5_items:4>, <projecte:matter_block:1>, <projecte:matter_block:1>], [<ore:plasticPurple>, <extraplanets:tier5_items:4>, <erebus:rein_exo>, <ore:runeGreedB>, <ore:pcb>, <ore:bRedString>, <erebus:rein_exo>, <extraplanets:tier5_items:4>, <ore:plasticPurple>], [<projectex:matter:4>, <extraplanets:tier6_items:4>, <ore:runeGreedB>, <ore:ingotUltimate>, <projectex:matter:5>, <ore:ingotUltimate>, <ore:bRedString>, <extraplanets:tier6_items:4>, <projectex:matter:3>], [<ore:blockSulfur>, <ore:gemWhiteGem>, <ore:pcb>, <projectex:matter:5>, <projecte:transmutation_table>.noReturn(), <projectex:matter:5>, <ore:pcb>, <ore:gemWhiteGem>, <ore:blockSulfur>], [<projectex:matter:3>, <extraplanets:tier6_items:4>, <ore:bRedString>, <ore:ingotUltimate>, <projectex:matter:5>, <ore:ingotUltimate>, <ore:runeGreedB>, <extraplanets:tier6_items:4>, <projectex:matter:4>], [<ore:plasticPurple>, <extraplanets:tier5_items:4>, <erebus:rein_exo>, <ore:bRedString>, <ore:pcb>, <ore:runeGreedB>, <erebus:rein_exo>, <extraplanets:tier5_items:4>, <ore:plasticPurple>], [<projecte:matter_block:1>, <projecte:matter_block:1>, <extraplanets:tier5_items:4>, <extraplanets:tier6_items:4>, <ore:gemWhiteGem>, <extraplanets:tier6_items:4>, <extraplanets:tier5_items:4>, <projecte:matter_block:1>, <projecte:matter_block:1>], [<projecte:matter_block:1>, <projecte:matter_block:1>, <ore:oc:craftingUpgrade>, <projectex:matter:4>, <ore:oc:craftingUpgrade>, <projectex:matter:3>, <ore:oc:craftingUpgrade>, <projecte:matter_block:1>, <projecte:matter_block:1>]]);

//book of knowledge
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:item.pe_tome>, [[<extraplanets:wafer:3>, <ore:gemGreenDiamond>, <apotheosis:hellshelf>, <forge:bucketfilled>.withTag({FluidName:"experience",Amount:1000}), <apotheosis:hellshelf>, <forge:bucketfilled>.withTag({FluidName:"experience",Amount:1000}), <apotheosis:hellshelf>, <ore:gemGreenDiamond>, <extraplanets:wafer:3>], [<ore:gemGreenDiamond>, <projectex:matter:10>, <ore:ingotInfinity>, <minecraft:chorus_fruit_popped>, <abyssalcraft:lifecrystal>, <minecraft:chorus_fruit_popped>, <ore:ingotInfinity>, <projectex:matter:10>, <ore:gemGreenDiamond>], [<apotheosis:hellshelf>, <ore:ingotUnstable>, <minecraft:chorus_fruit_popped>, <projectex:matter:11>, <draconicevolution:awakened_core>, <projectex:matter:11>, <minecraft:chorus_fruit_popped>, <ore:ingotUnstable>, <apotheosis:hellshelf>], [<appliedenergistics2:molecular_assembler>, <extracells:storage.component:3>, <projectex:matter:11>, <astralsorcery:itemcoloredlens:6>, <bloodmagic:sigil_seer>, <astralsorcery:itemcoloredlens:6>, <projectex:matter:11>, <extracells:storage.component:3>, <appliedenergistics2:molecular_assembler>], [<apotheosis:hellshelf>, <ore:blockTerrasteel>, <projectex:matter:10>, <bloodmagic:sigil_seer>, <projecte:item.pe_transmutation_tablet>.noReturn(), <bloodmagic:sigil_seer>, <projectex:matter:10>, <ore:blockTerrasteel>, <apotheosis:hellshelf>], [<appliedenergistics2:molecular_assembler>, <extracells:storage.component:3>, <projectex:matter:11>, <astralsorcery:itemcoloredlens:6>, <bloodmagic:sigil_seer>, <astralsorcery:itemcoloredlens:6>, <projectex:matter:11>, <extracells:storage.component:3>, <appliedenergistics2:molecular_assembler>], [<apotheosis:hellshelf>, <ore:ingotUnstable>, <minecraft:chorus_fruit_popped>, <projectex:matter:11>, <draconicevolution:awakened_core>, <projectex:matter:11>, <minecraft:chorus_fruit_popped>, <ore:ingotUnstable>, <apotheosis:hellshelf>], [<ore:gemGreenDiamond>, <projectex:matter:10>, <ore:ingotInfinity>, <minecraft:chorus_fruit_popped>, <abyssalcraft:lifecrystal>, <minecraft:chorus_fruit_popped>, <ore:ingotInfinity>, <projectex:matter:10>, <ore:gemGreenDiamond>], [<extraplanets:wafer:3>, <ore:gemGreenDiamond>, <apotheosis:hellshelf>, <minecraft:potion>.withTag({Potion:"apotheosis:strong_knowledge"}), <apotheosis:hellshelf>, <minecraft:potion>.withTag({Potion:"apotheosis:strong_knowledge"}), <apotheosis:hellshelf>, <ore:gemGreenDiamond>, <extraplanets:wafer:3>]]);

//crystal matrix ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:1>, [[<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <extraplanets:tier5_items:12>, <avaritia:resource>, <extraplanets:tier5_items:12>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [<projectex:matter:5>, <extraplanets:tier5_items:12>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <extraplanets:tier5_items:12>, <projectex:matter:5>], [<ore:runeSummerB>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <draconicevolution:draconic_core>, <actuallyadditions:item_crystal_empowered:5>, <draconicevolution:draconic_core>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:runeSummerB>], [<projectex:matter:5>, <extraplanets:tier5_items:12>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <actuallyadditions:item_crystal_empowered:5>, <extraplanets:tier5_items:12>, <projectex:matter:5>], [<avaritia:resource>, <ore:runeSummerB>, <draconicevolution:draconic_core>, <extraplanets:tier5_items:12>, <avaritia:resource>, <extraplanets:tier5_items:12>, <draconicevolution:draconic_core>, <ore:runeSummerB>, <avaritia:resource>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//ultimate ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:material:32>, [[<ore:ingotAstralStarmetal>, <projectex:matter:7>, <botania:quartztypemana>, <botania:quartztypesunny>, <botania:quartztypered>, <botania:quartztypesunny>, <botania:quartztypemana>, <projectex:matter:7>, <ore:ingotAstralStarmetal>], [<projectex:matter:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypeelf>, <botania:quartztypelavender>, <botania:quartztypeelf>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <projectex:matter:7>], [<astralsorcery:itemcraftingcomponent:4>, <botania:quartztypered>, <botania:quartztypelavender>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypelavender>, <botania:quartztypered>, <astralsorcery:itemcraftingcomponent:4>], [<projectex:matter:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <botania:quartztypeelf>, <botania:quartztypelavender>, <botania:quartztypeelf>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <projectex:matter:7>], [<ore:ingotAstralStarmetal>, <projectex:matter:7>, <botania:quartztypemana>, <botania:quartztypesunny>, <botania:quartztypered>, <botania:quartztypesunny>, <botania:quartztypemana>, <projectex:matter:7>, <ore:ingotAstralStarmetal>], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//neutron collector
recipes.remove(<avaritia:neutron_collector>);
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:neutron_collector>, [
[<ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockCertusQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>],
[<ore:blockIron>, <ore:ingotUltimate>, <draconicevolution:awakened_core>, <extrautils2:terraformer:5>, <extraplanets:tier10_items:4>, <extrautils2:terraformer:5>, <draconicevolution:awakened_core>, <ore:ingotUltimate>, <ore:blockIron>],
[<ore:blockIron>, <draconicevolution:awakened_core>, <extrautils2:terraformer:5>, <ore:ingotDemonicMetal>, <ore:blockElectrotineAlloy>, <ore:ingotDemonicMetal>, <extrautils2:terraformer:5>, <draconicevolution:awakened_core>, <ore:blockIron>],
[<ore:blockIron>, <extrautils2:terraformer:5>, <ore:ingotDemonicMetal>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <ore:ingotDemonicMetal>, <extrautils2:terraformer:5>, <ore:blockIron>],
[<ore:blockQuartz>, <extraplanets:tier10_items:4>, <ore:blockElectrotineAlloy>, <abyssalcraft:crystalcluster:11>, <ore:blockElectrotineAlloy>, <abyssalcraft:crystalcluster:11>, <ore:blockElectrotineAlloy>, <extraplanets:tier10_items:4>, <ore:blockQuartz>],
[<ore:blockIron>, <tp:lava_infused_stone>, <ore:ingotDemonicMetal>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <abyssalcraft:crystalcluster:11>, <ore:ingotDemonicMetal>, <tp:lava_infused_stone>, <ore:blockIron>],
[<ore:blockIron>, <draconicevolution:awakened_core>, <tp:lava_infused_stone>, <ore:ingotDemonicMetal>, <ore:blockElectrotineAlloy>, <ore:ingotDemonicMetal>, <tp:lava_infused_stone>, <draconicevolution:awakened_core>, <ore:blockIron>],
[<ore:blockIron>, <ore:ingotUltimate>, <draconicevolution:awakened_core>, <tp:lava_infused_stone>, <extraplanets:tier10_items:4>, <tp:lava_infused_stone>, <draconicevolution:awakened_core>, <ore:ingotUltimate>, <ore:blockIron>],
[<ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>, <ore:blockIron>, <ore:blockIron>, <ore:blockIron>, <ore:blockQuartz>]]);

//energy condenser mk1
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:condenser_mk1>, [[<ore:blockInsanium>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <ore:blockInsanium>], [<lordcraft:util:4>, <ore:platePlatinum>, <ore:matterDark>, <appliedenergistics2:smooth_sky_stone_chest>, <appliedenergistics2:smooth_sky_stone_chest>, <appliedenergistics2:smooth_sky_stone_chest>, <ore:matterDark>, <ore:platePlatinum>, <lordcraft:util:4>], [<lordcraft:util:4>, <ore:matterDark>, <projectex:matter:1>, <actuallyadditions:item_crystal_empowered:4>, <ore:platePlatinum>, <actuallyadditions:item_crystal_empowered:4>, <projectex:matter:1>, <ore:matterDark>, <lordcraft:util:4>], [<lordcraft:util:4>, <draconicevolution:infused_obsidian>, <actuallyadditions:item_crystal_empowered:4>, <actuallyadditions:item_crystal_empowered:4>, <ore:siphon>, <actuallyadditions:item_crystal_empowered:4>, <actuallyadditions:item_crystal_empowered:4>, <draconicevolution:infused_obsidian>, <lordcraft:util:4>], [<lordcraft:util:4>, <draconicevolution:infused_obsidian>, <ore:platePlatinum>, <ore:siphon>, <projecte:alchemical_chest>, <ore:siphon>, <ore:platePlatinum>, <draconicevolution:infused_obsidian>, <lordcraft:util:4>], [<lordcraft:util:4>, <draconicevolution:infused_obsidian>, <actuallyadditions:item_crystal_empowered:4>, <actuallyadditions:item_crystal_empowered:4>, <ore:siphon>, <actuallyadditions:item_crystal_empowered:4>, <actuallyadditions:item_crystal_empowered:4>, <draconicevolution:infused_obsidian>, <lordcraft:util:4>], [<lordcraft:util:4>, <ore:matterDark>, <projectex:matter:1>, <actuallyadditions:item_crystal_empowered:4>, <ore:platePlatinum>, <actuallyadditions:item_crystal_empowered:4>, <projectex:matter:1>, <ore:matterDark>, <lordcraft:util:4>], [<lordcraft:util:4>, <ore:platePlatinum>, <ore:matterDark>, <draconicevolution:infused_obsidian>, <draconicevolution:infused_obsidian>, <draconicevolution:infused_obsidian>, <ore:matterDark>, <ore:platePlatinum>, <lordcraft:util:4>], [<ore:blockInsanium>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <lordcraft:util:4>, <ore:blockInsanium>]]);

//energy condenser mk2
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:condenser_mk2>, [[<quantumflux:craftingpiece:4>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <quantumflux:craftingpiece:4>], [<lordcraft:util:5>, <ore:matterRed>, <overloaded:compressed_obsidian:5>, <ironchest:iron_chest:5>, <ironchest:iron_chest:5>, <ironchest:iron_chest:5>, <overloaded:compressed_obsidian:5>, <ore:matterRed>, <lordcraft:util:5>], [<lordcraft:util:5>, <overloaded:compressed_obsidian:5>, <ore:matterRed>, <xreliquary:mob_ingredient:3>, <extrautils2:user>, <xreliquary:mob_ingredient:3>, <ore:matterRed>, <overloaded:compressed_obsidian:5>, <lordcraft:util:5>], [<lordcraft:util:5>, <draconicevolution:infused_obsidian>, <xreliquary:mob_ingredient:3>, <projectex:matter:4>, <extrautils2:user>, <projectex:matter:4>, <xreliquary:mob_ingredient:3>, <draconicevolution:infused_obsidian>, <lordcraft:util:5>], [<lordcraft:util:5>, <draconicevolution:infused_obsidian>, <ore:xuUpgradeSpeedEnchanted>, <ore:xuUpgradeSpeedEnchanted>, <projecte:condenser_mk1>, <ore:xuUpgradeSpeedEnchanted>, <ore:xuUpgradeSpeedEnchanted>, <draconicevolution:infused_obsidian>, <lordcraft:util:5>], [<lordcraft:util:5>, <draconicevolution:infused_obsidian>, <xreliquary:mob_ingredient:3>, <projectex:matter:4>, <extrautils2:user>, <projectex:matter:4>, <xreliquary:mob_ingredient:3>, <draconicevolution:infused_obsidian>, <lordcraft:util:5>], [<lordcraft:util:5>, <overloaded:compressed_obsidian:5>, <ore:matterRed>, <xreliquary:mob_ingredient:3>, <extrautils2:user>, <xreliquary:mob_ingredient:3>, <ore:matterRed>, <overloaded:compressed_obsidian:5>, <lordcraft:util:5>], [<lordcraft:util:5>, <ore:matterRed>, <overloaded:compressed_obsidian:5>, <draconicevolution:infused_obsidian>, <draconicevolution:infused_obsidian>, <draconicevolution:infused_obsidian>, <overloaded:compressed_obsidian:5>, <ore:matterRed>, <lordcraft:util:5>], [<quantumflux:craftingpiece:4>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <lordcraft:util:5>, <quantumflux:craftingpiece:4>]]);

//infinity ingot
recipes.remove(<avaritia:resource:6>);
mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:6>, [
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>],
[<ore:ingotUltimate>, <avaritia:resource:5>, <abyssalcraft:crystalcluster:14>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <abyssalcraft:crystalcluster:14>, <avaritia:resource:5>, <ore:ingotUltimate>],
[<extraplanets:wafer:5>, <projectex:matter:10>, <avaritia:resource:5>, <avaritia:resource:5>, <projectex:matter:10>, <avaritia:resource:5>, <avaritia:resource:5>, <projectex:matter:10>, <extraplanets:wafer:5>],
[<ore:ingotUltimate>, <avaritia:resource:5>, <abyssalcraft:crystalcluster:14>, <eternalsingularity:eternal_singularity>, <avaritia:resource:5>, <eternalsingularity:eternal_singularity>, <abyssalcraft:crystalcluster:14>, <avaritia:resource:5>, <ore:ingotUltimate>],
[<ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>, <ore:ingotUltimate>, <ore:ingotCosmicNeutronium>],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);

//chaos catalyst
mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:chaos_catalyst>, [[<ore:ingotCosmicNeutronium>, <avaritia:resource:5>, <draconicevolution:chaotic_core>, <projectex:matter:11>, <ore:circuitUltimate>, <ore:alloyUltimate>, <ore:waferBasic>, <ore:waferAdvanced>, <extraplanets:wafer:5>], [<extraplanets:wafer>, <extraplanets:wafer:1>, <extraplanets:wafer:2>, <extraplanets:wafer:3>, <extraplanets:wafer:4>, <bloodmagic:slate:4>, <ore:blockTerrasteel>, <ore:ingotPlatinum>, <ore:ingotIridium>], [<ore:ingotLumium>, <ore:ingotSignalum>, <ore:ingotEnderium>, <enderio:item_capacitor_stellar>, <ore:itemAttractorCrystal>, <astralsorcery:itemusabledust:1>, <projecte:item.pe_body_stone>.reuse(), <projecte:item.pe_soul_stone>.reuse(), <projecte:item.pe_mind_stone>.reuse()], [<projecte:item.pe_life_stone>.reuse(), <ore:ingotEthaxium>, <ore:ingotLiquifiedCoralium>, <ore:ingotAbyssalnite>, <ore:ingotDreadium>, <lordcraft:inscription_tile>, <ore:elvenPixieDust>, <ore:elvenDragonstone>, <ore:ingotElvenElementium>], [<ore:ingotZirconium>, <ore:ingotBeryllium>, <ore:ingotLithium>, <ore:ingotMagnesiumDiboride>, <ore:ingotZircaloy>, <ore:ingotHSLASteel>, <ore:plasticBrown>, <ore:gearIronCompressed>, <ore:ingotHOPGraphite>], [<ore:wireCopper>, <ore:wireElectrum>, <ore:wireAluminum>, <ore:wireSteel>, <magneticraft:crafting:5>, <magneticraft:crafting:4>, <actuallyadditions:item_misc:24>, <erebus:materials:41>, <ore:bamboo>], [<exnihilocreatio:item_doll:7>, <mysticalagradditions:stuff:69>, <yabba:upgrade_star_tier>, <embers:flame_barrier>, <industrialforegoing:pink_slime_ingot>, <ore:ingotFiery>, <twilightforest:naga_scale>, <ore:ingotLandium>, <ore:gemRime>], [<ore:gemAmethyst>, <rftoolsdim:time_absorber>, <ore:oc:cpu3>, <ore:oc:graphicsCard3>, <appliedenergistics2:material:47>, null, null, null, null], [null, null, null, null, null, null, null, null, null]]);

//chaos ingot
mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:chaos_ingot>, [[<ore:ingotLudicrite>, <ore:ingotCosmicNeutronium>, <ore:ingotLudicrite>, <ore:ingotCosmicNeutronium>, <ore:ingotLudicrite>, null, null, null, null], [<projectex:matter:11>, <contenttweaker:chaos_catalyst>, <ore:ingotInfinity>, <contenttweaker:chaos_catalyst>, <projectex:matter:11>, null, null, null, null], [<ore:ingotLudicrite>, <ore:ingotInfinity>, <contenttweaker:chaos_catalyst>, <ore:ingotInfinity>, <ore:ingotLudicrite>, null, null, null, null], [<projectex:matter:11>, <contenttweaker:chaos_catalyst>, <extraplanets:tier8_items:4>, <contenttweaker:chaos_catalyst>, <projectex:matter:11>, null, null, null, null], [<ore:ingotLudicrite>, <avaritiatweaks:gaia_block>, <contenttweaker:chaos_catalyst>, <avaritiatweaks:gaia_block>, <ore:ingotLudicrite>, null, null, null, null], [<projectex:matter:11>, <contenttweaker:chaos_catalyst>, <extraplanets:tier8_items:4>, <contenttweaker:chaos_catalyst>, <projectex:matter:11>, null, null, null, null], [<ore:ingotLudicrite>, <ore:ingotInfinity>, <contenttweaker:chaos_catalyst>, <ore:ingotInfinity>, <ore:ingotLudicrite>, null, null, null, null], [<projectex:matter:11>, <contenttweaker:chaos_catalyst>, <ore:ingotInfinity>, <contenttweaker:chaos_catalyst>, <projectex:matter:11>, null, null, null, null], [<ore:ingotLudicrite>, <ore:ingotCosmicNeutronium>, <ore:ingotLudicrite>, <ore:ingotCosmicNeutronium>, <ore:ingotLudicrite>, null, null, null, null]]);

//wand of animation
mods.extendedcrafting.TableCrafting.addShaped(0, <erebus:wand_of_animation>, [[null, null, null, null, <erebus:materials:12>, <erebus:materials:41>, <erebus:materials:15>, <projectex:matter:7>, <projectex:matter:7>], [null, null, null, null, <mysticalagradditions:stuff:69>, <projectex:matter:7>, <extendedcrafting:singularity_custom:310>, <ore:plasticYellow>, <projectex:matter:7>], [null, null, null, <ore:gemJade>, <ore:ingotCrystaltine>, <industrialforegoing:mob_duplicator>, <extrautils2:opinium:5>, <extendedcrafting:singularity_custom:310>, <erebus:materials:15>], [null, null, null, <ore:ingotCrystallinePinkSlime>, <projectex:matter:7>, <erebus:materials:64>, <industrialforegoing:mob_duplicator>, <projectex:matter:7>, <erebus:materials:41>], [null, null, <mysticalagradditions:stuff:69>, <ore:plateElectrumFlux>, <lordcraft:staff_earth:17>, <projectex:matter:7>, <ore:ingotCrystaltine>, <mysticalagradditions:stuff:69>, <erebus:materials:12>], [null, <ore:bamboo>, <ore:plateElectrumFlux>, <bloodmagic:slate:4>, <ore:plateElectrumFlux>, <ore:ingotCrystallinePinkSlime>, <ore:gemJade>, null, null], [<mysticalagradditions:stuff:69>, <ore:plateElectrumFlux>, <bloodmagic:slate:4>, <ore:plateElectrumFlux>, <mysticalagradditions:stuff:69>, null, null, null, null], [<projectex:matter:7>, <botania:floatingspecialflower>.withTag({type:"tangleberrie"}), <ore:plateElectrumFlux>, <ore:bamboo>, null, null, null, null, null], [<projectex:matter:7>, <projectex:matter:7>, <mysticalagradditions:stuff:69>, null, null, null, null, null, null]]);

//infinity tank
recipes.remove(<overloaded:infinite_tank>);

mods.extendedcrafting.TableCrafting.addShaped(0, <overloaded:infinite_tank>, [[<ore:ingotGarfax>, <extraplanets:wafer>, <ore:ingotBlutonium>, <ore:ingotVividAlloy>, <ore:ingotVividAlloy>, <ore:ingotVividAlloy>, <ore:ingotBlutonium>, <extraplanets:wafer>, <ore:ingotGarfax>], [<extraplanets:wafer>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <extraplanets:wafer>], [<ore:ingotBlutonium>, <actuallyadditions:item_crystal_empowered:1>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <ore:ingotElectrotineAlloy>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <actuallyadditions:item_crystal_empowered:1>, <ore:ingotBlutonium>], [<ore:ingotVividAlloy>, <actuallyadditions:item_crystal_empowered:1>, <mekanism:basicblock:9>, <overloaded:fluid_core>, <ore:ingotPlatinum>, <overloaded:fluid_core>, <mekanism:basicblock:9>, <actuallyadditions:item_crystal_empowered:1>, <ore:ingotVividAlloy>], [<ore:ingotVividAlloy>, <actuallyadditions:item_crystal_empowered:1>, <mekanism:basicblock:9>, <ore:ingotElectrotineAlloy>, <bloodmagic:blood_tank:15>, <ore:ingotElectrotineAlloy>, <mekanism:basicblock:9>, <actuallyadditions:item_crystal_empowered:1>, <ore:ingotVividAlloy>], [<ore:ingotVividAlloy>, <actuallyadditions:item_crystal_empowered:1>, <mekanism:basicblock:9>, <overloaded:fluid_core>, <ore:ingotPlatinum>, <overloaded:fluid_core>, <mekanism:basicblock:9>, <actuallyadditions:item_crystal_empowered:1>, <ore:ingotVividAlloy>], [<ore:ingotBlutonium>, <actuallyadditions:item_crystal_empowered:1>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <ore:ingotElectrotineAlloy>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <actuallyadditions:item_crystal_empowered:1>, <ore:ingotBlutonium>], [<extraplanets:wafer>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <ore:ingotPlatinum>, <mekanism:basicblock:9>, <extraplanets:wafer>], [<ore:ingotGarfax>, <extraplanets:wafer>, <ore:ingotBlutonium>, <ore:ingotVividAlloy>, <ore:ingotVividAlloy>, <ore:ingotVividAlloy>, <ore:ingotBlutonium>, <extraplanets:wafer>, <ore:ingotGarfax>]]);

//infinity barrel
recipes.remove(<overloaded:infinite_barrel>);

mods.extendedcrafting.TableCrafting.addShaped(0, <overloaded:infinite_barrel>, [[<ore:ingotSoularium>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotSoularium>], [<ore:ingotBronze>, <quantumstorage:quantum_storage_unit>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <quantumstorage:quantum_storage_unit>, <ore:ingotBronze>], [<ore:ingotBronze>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <extraplanets:wafer:2>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <ore:ingotBronze>], [<ore:ingotBronze>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <overloaded:item_core>, <extraplanets:wafer:2>, <overloaded:item_core>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <ore:ingotBronze>], [<ore:ingotBronze>, <pneumaticcraft:transistor>, <extraplanets:wafer:2>, <extraplanets:wafer:2>, <extracells:storage.physical:3>, <extraplanets:wafer:2>, <extraplanets:wafer:2>, <pneumaticcraft:transistor>, <ore:ingotBronze>], [<ore:ingotBronze>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <overloaded:item_core>, <extraplanets:wafer:2>, <overloaded:item_core>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <ore:ingotBronze>], [<ore:ingotBronze>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <extraplanets:wafer:2>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <ore:ingotBronze>], [<ore:ingotBronze>, <quantumstorage:quantum_storage_unit>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <actuallyadditions:block_giant_chest_large>, <pneumaticcraft:transistor>, <quantumstorage:quantum_storage_unit>, <ore:ingotBronze>], [<ore:ingotSoularium>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotConstantan>, <ore:ingotSoularium>]]);

//infinity capacitor
recipes.remove(<overloaded:infinite_capacitor>);

mods.extendedcrafting.TableCrafting.addShaped(0, <overloaded:infinite_capacitor>, [[<ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <mekanism:basicblock2:3>, <enderio:item_basic_capacitor:2>, <mekanism:basicblock2:3>, <pneumaticcraft:capacitor>, <mekanism:basicblock2:3>, <enderio:item_basic_capacitor:2>, <mekanism:basicblock2:3>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <enderio:item_basic_capacitor:2>, <immersiveengineering:metal_device0:2>, <enderio:item_capacitor_vivid>, <mekanism:basicblock2:3>, <enderio:item_capacitor_vivid>, <immersiveengineering:metal_device0:2>, <enderio:item_basic_capacitor:2>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <mekanism:basicblock2:3>, <enderio:item_capacitor_vivid>, <overloaded:energy_core>, <quantumflux:craftingpiece:5>, <overloaded:energy_core>, <enderio:item_capacitor_vivid>, <mekanism:basicblock2:3>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <pneumaticcraft:capacitor>, <mekanism:basicblock2:3>, <quantumflux:craftingpiece:5>, <enderio:item_capacitor_stellar>, <quantumflux:craftingpiece:5>, <mekanism:basicblock2:3>, <pneumaticcraft:capacitor>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <mekanism:basicblock2:3>, <enderio:item_capacitor_vivid>, <overloaded:energy_core>, <quantumflux:craftingpiece:5>, <overloaded:energy_core>, <enderio:item_capacitor_vivid>, <mekanism:basicblock2:3>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <enderio:item_basic_capacitor:2>, <immersiveengineering:metal_device0:2>, <enderio:item_capacitor_vivid>, <mekanism:basicblock2:3>, <enderio:item_capacitor_vivid>, <immersiveengineering:metal_device0:2>, <enderio:item_basic_capacitor:2>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <mekanism:basicblock2:3>, <enderio:item_basic_capacitor:2>, <mekanism:basicblock2:3>, <pneumaticcraft:capacitor>, <mekanism:basicblock2:3>, <enderio:item_basic_capacitor:2>, <mekanism:basicblock2:3>, <ore:ingotFriscion>], [<ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>, <ore:ingotFriscion>]]);

//creative fluid tank
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:machineblock2:11>.withTag({tier: 4}), [[<mekanism:basicblock:9>, <ore:ingotInfinity>, <modularmachinery:blockfluidinputhatch:7>, <ore:ingotInfinity>, <modularmachinery:blockfluidoutputhatch:7>, <ore:ingotInfinity>, <modularmachinery:blockfluidinputhatch:7>, <ore:ingotInfinity>, <mekanism:basicblock:9>], [null, <ore:clumpOsmium>, <thermaldynamics:duct_16:6>, <extracells:storage.component:10>, <mekanism:transmitter:1>.withTag({tier:3}), <extracells:storage.component:10>, <thermaldynamics:duct_16:6>, <ore:clumpOsmium>, null], [<mekanism:basicblock:9>, <ore:clumpOsmium>, <extracells:storage.component:10>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <extracells:storage.component:10>, <ore:clumpOsmium>, <mekanism:basicblock:9>], [<modularmachinery:blockfluidinputhatch:7>, <mekanism:basicblock:9>, <mekanism:machineblock2:11>.withTag({tier:3}), <overloaded:infinite_tank>, <overloaded:infinite_tank>, <overloaded:infinite_tank>, <mekanism:machineblock2:11>.withTag({tier:3}), <mekanism:basicblock:9>, <modularmachinery:blockfluidinputhatch:7>], [<modularmachinery:blockfluidoutputhatch:7>, <mekanism:basicblock:9>, <mekanism:machineblock2:11>.withTag({tier:3}), <overloaded:infinite_tank>, <embers:block_tank>, <overloaded:infinite_tank>, <mekanism:machineblock2:11>.withTag({tier:3}), <mekanism:basicblock:9>, <modularmachinery:blockfluidoutputhatch:7>], [<modularmachinery:blockfluidinputhatch:7>, <mekanism:basicblock:9>, <mekanism:machineblock2:11>.withTag({tier:3}), <overloaded:infinite_tank>, <overloaded:infinite_tank>, <overloaded:infinite_tank>, <mekanism:machineblock2:11>.withTag({tier:3}), <mekanism:basicblock:9>, <modularmachinery:blockfluidinputhatch:7>], [<mekanism:basicblock:9>, <ore:clumpOsmium>, <extracells:storage.component:10>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <extracells:storage.component:10>, <ore:clumpOsmium>, <mekanism:basicblock:9>], [null, <ore:clumpOsmium>, <thermaldynamics:duct_16:6>, <extracells:storage.component:10>, <mekanism:transmitter:1>.withTag({tier:3}), <extracells:storage.component:10>, <thermaldynamics:duct_16:6>, <ore:clumpOsmium>, null], [<mekanism:basicblock:9>, <ore:ingotInfinity>, <modularmachinery:blockfluidinputhatch:7>, <ore:ingotInfinity>, <modularmachinery:blockfluidoutputhatch:7>, <ore:ingotInfinity>, <modularmachinery:blockfluidinputhatch:7>, <ore:ingotInfinity>, <mekanism:basicblock:9>]]);

//overloaded creative generator
mods.extendedcrafting.TableCrafting.addShaped(0, <overloaded:creative_generator>, [[<immersiveengineering:metal_decoration0:2>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotEnchantedMetal>, <thermaldynamics:duct_0:5>, <ore:ingotEnchantedMetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <immersiveengineering:metal_decoration0:2>], [<ore:ingotInfinity>, <ore:ingotMelodicAlloy>, <contenttweaker:chaos_ingot>, <ore:ingotElectricalSteel>, <overloaded:hyper_energy_sender>, <ore:ingotElectricalSteel>, <contenttweaker:chaos_ingot>, <ore:ingotMelodicAlloy>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:skullZombieController>, <ore:ingotElectricalSteel>, <ore:ingotThermoconducting>, <mysticalagradditions:stuff:69>, <ore:ingotThermoconducting>, <ore:ingotElectricalSteel>, <ore:skullZombieController>, <ore:ingotInfinity>], [<ore:ingotEnchantedMetal>, <ore:skullZombieController>, <ore:ingotElectricalSteel>, <ore:ingotThermoconducting>, <botania:spark>, <ore:ingotThermoconducting>, <ore:ingotElectricalSteel>, <ore:skullZombieController>, <ore:ingotEnchantedMetal>], [<mekanism:energycube>.withTag({tier:3}), <overloaded:hyper_energy_sender>, <mysticalagradditions:stuff:69>, <extrautils2:rainbowgenerator>, <overloaded:infinite_capacitor>, <extrautils2:rainbowgenerator>, <mysticalagradditions:stuff:69>, <overloaded:hyper_energy_sender>, <mekanism:energycube>.withTag({tier:3})], [<ore:ingotEnchantedMetal>, <ore:skullZombieController>, <ore:ingotElectricalSteel>, <ore:ingotThermoconducting>, <botania:spark>, <ore:ingotThermoconducting>, <ore:ingotElectricalSteel>, <ore:skullZombieController>, <ore:ingotEnchantedMetal>], [<ore:ingotInfinity>, <ore:skullZombieController>, <ore:ingotElectricalSteel>, <ore:ingotThermoconducting>, <mysticalagradditions:stuff:69>, <ore:ingotThermoconducting>, <ore:ingotElectricalSteel>, <ore:skullZombieController>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotMelodicAlloy>, <contenttweaker:chaos_ingot>, <ore:ingotElectricalSteel>, <overloaded:hyper_energy_sender>, <ore:ingotElectricalSteel>, <contenttweaker:chaos_ingot>, <ore:ingotMelodicAlloy>, <ore:ingotInfinity>], [<immersiveengineering:metal_decoration0:2>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotEnchantedMetal>, <thermaldynamics:duct_0:5>, <ore:ingotEnchantedMetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <immersiveengineering:metal_decoration0:2>]]);

//creative mill
mods.extendedcrafting.TableCrafting.addShaped(0, <extrautils2:passivegenerator:6>, [[<botania:pylon:2>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotDemonicMetal>, <ore:ingotUnstable>, <ore:ingotDemonicMetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <botania:pylon:2>], [<ore:ingotInfinity>, <ore:compressed2xCobblestone>, <ore:compressed2xCobblestone>, <extrautils2:passivegenerator:3>, <mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:5>, <overloaded:compressed_stone:1>, <overloaded:compressed_stone:1>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:passivegenerator:3>, <mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:5>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <ore:ingotInfinity>], [<ore:ingotEnchantedMetal>, <ore:compressed2xGravel>, <ore:compressed2xGravel>, <embers:superheater>, <astralsorcery:itemshiftingstar>.withTag({astralsorcery: {starAttunement: "astralsorcery.constellation.armara"}}), <embers:superheater>, <ore:compressed2xNetherrack>, <ore:compressed2xNetherrack>, <ore:ingotEnchantedMetal>], [<darkutils:material:1>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:8>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <darkutils:material:1>], [<ore:ingotEnchantedMetal>, <ore:compressed2xSand>, <ore:compressed2xSand>, <embers:superheater>, <astralsorcery:itemshiftingstar>.withTag({astralsorcery: {starAttunement: "astralsorcery.constellation.armara"}}), <embers:superheater>, <ore:compressed2xDirt>, <ore:compressed2xDirt>, <ore:ingotEnchantedMetal>], [<ore:ingotInfinity>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:passivegenerator:2>, <mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:4>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:compressed1xDust>, <ore:compressed1xDust>, <extrautils2:passivegenerator:2>, <mysticalagradditions:stuff:69>, <extrautils2:passivegenerator:4>, <overloaded:compressed_obsidian:1>, <overloaded:compressed_obsidian:1>, <ore:ingotInfinity>], [<botania:pylon:2>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotDemonicMetal>, <ore:ingotUnstable>, <ore:ingotDemonicMetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <botania:pylon:2>]]);

//Energy Cell
mods.extendedcrafting.TableCrafting.addShaped(0, <appliedenergistics2:creative_energy_cell>, [[<appliedenergistics2:fluix_block>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotKnightmetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <appliedenergistics2:fluix_block>], [<ore:ingotInfinity>, <bloodmagic:blood_rune>, <appliedenergistics2:smooth_sky_stone_block>, <ore:blockInsanium>, <ore:ingotPalladium>, <ore:blockInsanium>, <appliedenergistics2:smooth_sky_stone_block>, <bloodmagic:blood_rune>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:34>, <appliedenergistics2:smooth_sky_stone_block>, <ore:ingotPalladium>, <appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:34>, <appliedenergistics2:smooth_sky_stone_block>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <mysticalagriculture:witherproof_block>, <appliedenergistics2:smooth_sky_stone_block>, <mysticalagradditions:stuff:69>, <appliedenergistics2:dense_energy_cell>, <mysticalagradditions:stuff:69>, <appliedenergistics2:smooth_sky_stone_block>, <mysticalagriculture:witherproof_block>, <ore:ingotInfinity>], [<ore:ingotKnightmetal>, <ore:ingotPalladium>, <ore:ingotPalladium>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:dense_energy_cell>, <ore:ingotPalladium>, <ore:ingotPalladium>, <ore:ingotKnightmetal>], [<ore:ingotInfinity>, <mysticalagriculture:witherproof_block>, <appliedenergistics2:smooth_sky_stone_block>, <mysticalagradditions:stuff:69>, <appliedenergistics2:dense_energy_cell>, <mysticalagradditions:stuff:69>, <appliedenergistics2:smooth_sky_stone_block>, <mysticalagriculture:witherproof_block>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:34>, <appliedenergistics2:smooth_sky_stone_block>, <ore:ingotPalladium>, <appliedenergistics2:smooth_sky_stone_block>, <appliedenergistics2:material:34>, <appliedenergistics2:smooth_sky_stone_block>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <bloodmagic:blood_rune>, <appliedenergistics2:smooth_sky_stone_block>, <ore:blockInsanium>, <ore:ingotPalladium>, <ore:blockInsanium>, <appliedenergistics2:smooth_sky_stone_block>, <bloodmagic:blood_rune>, <ore:ingotInfinity>], [<appliedenergistics2:fluix_block>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotKnightmetal>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <appliedenergistics2:fluix_block>]]);

//infinite energy (electricity)
mods.extendedcrafting.TableCrafting.addShaped(0, <magneticraft:infinite_energy>, [[<magneticraft:crafting:1>, <immersiveengineering:metal_decoration0:6>, <magneticraft:electric_heater>, <ore:heavyPlateTungsten>, <ore:blockSheetmetalUranium>, <ore:heavyPlateTungsten>, <magneticraft:electric_heater>, <immersiveengineering:metal_decoration0:6>, <magneticraft:crafting:1>], [<immersiveengineering:metal_decoration0:6>, <magneticraft:crafting:3>, <ore:gearDark>, <ore:gearElectrumFlux>, <immersiveengineering:connector:4>, <ore:gearElectrumFlux>, <ore:gearDark>, <magneticraft:crafting:3>, <immersiveengineering:metal_decoration0:6>], [<magneticraft:electric_heater>, <ore:dustLunar>, <mysticalagradditions:stuff:69>, <ore:crystalZinc>, <quantumflux:craftingpiece:6>, <ore:crystalZinc>, <mysticalagradditions:stuff:69>, <ore:dustLunar>, <magneticraft:electric_heater>], [<ore:heavyPlateTungsten>, <ore:gearElectrumFlux>, <ore:circuitUltimate>, <ore:ingotInfinity>, <ore:stickSteel>, <ore:ingotInfinity>, <ore:circuitUltimate>, <ore:gearElectrumFlux>, <ore:heavyPlateTungsten>], [<thermaldynamics:duct_48>, <immersiveengineering:connector:4>, <quantumflux:craftingpiece:6>, <actuallyadditions:item_crystal_empowered:5>, <ore:ingotInfinity>, <actuallyadditions:item_crystal_empowered:5>, <quantumflux:craftingpiece:6>, <immersiveengineering:connector:4>, <thermaldynamics:duct_48>], [<ore:heavyPlateTungsten>, <ore:gearElectrumFlux>, <ore:circuitUltimate>, <ore:ingotInfinity>, <ore:stickSteel>, <ore:ingotInfinity>, <ore:circuitUltimate>, <ore:gearElectrumFlux>, <ore:heavyPlateTungsten>], [<magneticraft:electric_heater>, <ore:dustLunar>, <mysticalagradditions:stuff:69>, <extendedcrafting:material:18>, <quantumflux:craftingpiece:6>, <extendedcrafting:material:18>, <mysticalagradditions:stuff:69>, <ore:dustLunar>, <magneticraft:electric_heater>], [<immersiveengineering:metal_decoration0:6>, <magneticraft:crafting:3>, <ore:gearDark>, <ore:gearElectrumFlux>, <immersiveengineering:connector:4>, <ore:gearElectrumFlux>, <ore:gearDark>, <magneticraft:crafting:3>, <immersiveengineering:metal_decoration0:6>], [<magneticraft:crafting:1>, <immersiveengineering:metal_decoration0:6>, <magneticraft:electric_heater>, <ore:heavyPlateTungsten>, <ore:blockSheetmetalUranium>, <ore:heavyPlateTungsten>, <magneticraft:electric_heater>, <immersiveengineering:metal_decoration0:6>, <magneticraft:crafting:1>]]);

//reactor coolant port
mods.extendedcrafting.TableCrafting.addShaped(0, <bigreactors:reactorcreativecoolantport>, [[<bigreactors:reactorcasing>, <botania:lightrelay>, <bigreactors:reactorcasing>, <ore:crystalSlag>, <bigreactors:reactorcasing>, <ore:crystalSlag>, <bigreactors:reactorcasing>, <botania:lightrelay>, <bigreactors:reactorcasing>], [<botania:lightrelay>, <ore:ingotMorganine>, <mysticalagradditions:stuff:69>, <ore:ingotInfinity>, <ore:ingotMorganine>, <ore:ingotInfinity>, <mysticalagradditions:stuff:69>, <ore:ingotMorganine>, <botania:lightrelay>], [<bigreactors:reactorcasing>, <mysticalagradditions:stuff:69>, <ore:crystalCinnabar>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:crystalCinnabar>, <mysticalagradditions:stuff:69>, <bigreactors:reactorcasing>], [<ore:crystalSlag>, <ore:ingotInfinity>, <ore:ingotInfinity>, <magneticraft:steam_boiler>, <magneticraft:steam_boiler>, <magneticraft:steam_boiler>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:crystalSlag>], [<bigreactors:reactorcasing>, <ore:ingotMorganine>, <ore:ingotInfinity>, <magneticraft:steam_boiler>, <ore:gearEnderium>, <magneticraft:steam_boiler>, <ore:ingotInfinity>, <ore:ingotMorganine>, <bigreactors:reactorcasing>], [<ore:crystalSlag>, <ore:ingotInfinity>, <ore:ingotInfinity>, <magneticraft:steam_boiler>, <magneticraft:steam_boiler>, <magneticraft:steam_boiler>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:crystalSlag>], [<bigreactors:reactorcasing>, <mysticalagradditions:stuff:69>, <ore:crystalCinnabar>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:crystalCinnabar>, <mysticalagradditions:stuff:69>, <bigreactors:reactorcasing>], [<abyssalcraft:materializer>, <ore:ingotMorganine>, <mysticalagradditions:stuff:69>, <ore:ingotInfinity>, <ore:ingotMorganine>, <ore:ingotInfinity>, <mysticalagradditions:stuff:69>, <ore:ingotMorganine>, <abyssalcraft:materializer>], [<bigreactors:reactorcasing>, <abyssalcraft:materializer>, <bigreactors:reactorcasing>, <ore:crystalSlag>, <bigreactors:reactorcasing>, <ore:crystalSlag>, <bigreactors:reactorcasing>, <abyssalcraft:materializer>, <bigreactors:reactorcasing>]]);

//turbine steam generator
mods.extendedcrafting.TableCrafting.addShaped(0, <bigreactors:turbinecreativesteamgenerator>, [[<bigreactors:turbinehousing>, <ore:circuitUltimate>, <bigreactors:turbinehousing>, <mekanismgenerators:generator:10>, <bigreactors:turbinehousing>, <mekanismgenerators:generator:10>, <bigreactors:turbinehousing>, <ore:circuitUltimate>, <bigreactors:turbinehousing>], [<ore:circuitUltimate>, <nuclearcraft:turbine_dynamo_coil:5>, <mysticalagradditions:stuff:69>, <ore:ingotInfinity>, <ore:ingotLudicrite>, <ore:ingotInfinity>, <mysticalagradditions:stuff:69>, <nuclearcraft:turbine_dynamo_coil:5>, <ore:circuitUltimate>], [<bigreactors:turbinehousing>, <mysticalagradditions:stuff:69>, <extraplanets:wafer:1>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <extraplanets:wafer:1>, <mysticalagradditions:stuff:69>, <bigreactors:turbinehousing>], [<mekanismgenerators:generator:10>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:gemVilliaumite>, <ore:chassis>, <ore:gemFluorite>, <ore:ingotInfinity>, <ore:ingotInfinity>, <mekanismgenerators:generator:10>], [<bigreactors:turbinehousing>, <ore:ingotLudicrite>, <ore:ingotInfinity>, <magneticraft:water_generator>, <bigreactors:reactorcreativecoolantport>, <magneticraft:water_generator>, <ore:ingotInfinity>, <ore:ingotLudicrite>, <bigreactors:turbinehousing>], [<mekanismgenerators:generator:10>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:gemFluorite>, <ore:steelFrame>, <ore:gemVilliaumite>, <ore:ingotInfinity>, <ore:ingotInfinity>, <mekanismgenerators:generator:10>], [<bigreactors:turbinehousing>, <mysticalagradditions:stuff:69>, <extraplanets:wafer:1>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <extraplanets:wafer:1>, <mysticalagradditions:stuff:69>, <bigreactors:turbinehousing>], [<thermalexpansion:dynamo>, <nuclearcraft:turbine_dynamo_coil:5>, <mysticalagradditions:stuff:69>, <ore:ingotInfinity>, <ore:ingotLudicrite>, <ore:ingotInfinity>, <mysticalagradditions:stuff:69>, <nuclearcraft:turbine_dynamo_coil:5>, <thermalexpansion:dynamo>], [<bigreactors:turbinehousing>, <thermalexpansion:dynamo>, <bigreactors:turbinehousing>, <mekanismgenerators:generator:10>, <bigreactors:turbinehousing>, <mekanismgenerators:generator:10>, <bigreactors:turbinehousing>, <thermalexpansion:dynamo>, <bigreactors:turbinehousing>]]);

//creative compressor
mods.extendedcrafting.TableCrafting.addShaped(0, <pneumaticcraft:creative_compressor>, [[<mekanism:polyethene:2>, <abyssalcraft:platec>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_valve>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_wall>, <abyssalcraft:platec>, <mekanism:polyethene:2>], [<abyssalcraft:platec>, <pneumaticcraft:advanced_air_compressor>, <ore:ingotInfinity>, <ore:plasticGray>, <ore:gearIronCompressed>, <ore:plasticGray>, <ore:ingotInfinity>, <pneumaticcraft:advanced_air_compressor>, <abyssalcraft:platec>], [<pneumaticcraft:pressure_chamber_wall>, <ore:ingotInfinity>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_pcb>, <ore:plasticBlack>, <pneumaticcraft:advanced_pcb>, <pneumaticcraft:advanced_liquid_compressor>, <ore:ingotInfinity>, <pneumaticcraft:pressure_chamber_wall>], [<pneumaticcraft:pressure_chamber_wall>, <ore:plasticGray>, <pneumaticcraft:advanced_pcb>, <pneumaticcraft:flux_compressor>, <mysticalagradditions:stuff:69>, <pneumaticcraft:flux_compressor>, <pneumaticcraft:advanced_pcb>, <ore:plasticGray>, <pneumaticcraft:pressure_chamber_wall>], [<pneumaticcraft:pressure_chamber_valve>, <ore:gearIronCompressed>, <nuclearcraft:pressurizer_idle>, <mysticalagradditions:stuff:69>, <bloodmagic:sigil_void>, <mysticalagradditions:stuff:69>, <nuclearcraft:pressurizer_idle>, <ore:gearIronCompressed>, <pneumaticcraft:pressure_chamber_valve>], [<pneumaticcraft:pressure_chamber_wall>, <ore:plasticGray>, <pneumaticcraft:advanced_pcb>, <pneumaticcraft:flux_compressor>, <mysticalagradditions:stuff:69>, <pneumaticcraft:flux_compressor>, <pneumaticcraft:advanced_pcb>, <ore:plasticGray>, <pneumaticcraft:pressure_chamber_wall>], [<pneumaticcraft:pressure_chamber_wall>, <ore:ingotInfinity>, <pneumaticcraft:advanced_liquid_compressor>, <pneumaticcraft:advanced_pcb>, <ore:plasticBlack>, <pneumaticcraft:advanced_pcb>, <pneumaticcraft:advanced_liquid_compressor>, <ore:ingotInfinity>, <pneumaticcraft:pressure_chamber_wall>], [<abyssalcraft:platec>, <pneumaticcraft:advanced_air_compressor>, <ore:ingotInfinity>, <ore:plasticGray>, <ore:gearIronCompressed>, <ore:plasticGray>, <ore:ingotInfinity>, <pneumaticcraft:advanced_air_compressor>, <abyssalcraft:platec>], [<mekanism:polyethene:2>, <abyssalcraft:platec>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_valve>, <pneumaticcraft:pressure_chamber_wall>, <pneumaticcraft:pressure_chamber_wall>, <abyssalcraft:platec>, <mekanism:polyethene:2>]]);

//chaos plank

mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:chaos_block>, [[<apotheosis:hellshelf>, <ore:blockInsaniumCoal>, <contenttweaker:chaos_ingot>, <ore:dustPyrotheum>, <contenttweaker:chaos_ingot>, <ore:dustCryotheum>, <contenttweaker:chaos_ingot>, <ore:blockInsaniumCoal>, <apotheosis:hellshelf>], [<lordcraft:runestone:226>, <ore:plankWood>, <draconicevolution:energy_crystal:2>, <ore:dustAerotheum>, <contenttweaker:chaos_ingot>, <ore:dustPetrotheum>, <draconicevolution:energy_crystal:2>, <ore:plankWood>, <lordcraft:runestone:226>], [<contenttweaker:chaos_ingot>, <projectex:final_star_shard>, <contenttweaker:omega_gem>, <contenttweaker:bear_metal>, <avaritiatweaks:enhancement_crystal>, <contenttweaker:bear_metal>, <contenttweaker:omega_gem>, <projectex:final_star_shard>, <contenttweaker:chaos_ingot>], [<yabba:upgrade_star_tier>, <ore:skullGuardianDiode>, <contenttweaker:sey_metal>, <overloaded:creative_generator>, <botania:pool:1>, <embers:creative_ember_source>, <contenttweaker:og_metal>, <ore:

skullGuardianDiode>, <yabba:upgrade_star_tier>], [<contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>, <bigreactors:reactorcreativecoolantport>, <bigreactors:turbinecreativesteamgenerator>, <erebus:wand_of_animation>, <extrautils2:passivegenerator:6>, <compacter:cobbler>, <contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>], [<botania:specialflower>.withTag({type:"asgardandelion"}), <ore:skullGuardianDiode>, <contenttweaker:sey_metal>, <appliedenergistics2:creative_energy_cell>, <pneumaticcraft:creative_compressor>, <mekanism:machineblock2:11>.withTag({tier:4}), <contenttweaker:og_metal>, <ore:skullGuardianDiode>, <botania:specialflower>.withTag({type:"asgardandelion"})], [<contenttweaker:chaos_ingot>, <projecte:nova_cataclysm>, <extrautils2:opinium:8>, <contenttweaker:caz_metal>, <tconstruct:materials:50>, <contenttweaker:caz_metal>, <extrautils2:opinium:8>, <projecte:nova_cataclysm>, <contenttweaker:chaos_ingot>], [<enderio:item_capacitor_stellar>, <ore:plankWood>, <abyssalcraft:odb>, <minecraft:spawn_egg>.withTag({EntityTag: {id: "erebus:erebus.crushroom"}}), <minecraft:spawn_egg>.withTag({EntityTag:{id:"bat"}}), <minecraft:spawn_egg>.withTag({EntityTag:{id:"twilightforest:maze_slime"}}), <abyssalcraft:odb>, <ore:plankWood>, <enderio:item_capacitor_stellar>], [<apotheosis:hellshelf>, <ore:itemAttractorCrystal>, <contenttweaker:chaos_ingot>, <ore:slimecrystal>, <ore:slimecrystal>, <ore:slimecrystal>, <contenttweaker:chaos_ingot>, <ore:itemAttractorCrystal>, <apotheosis:hellshelf>]]);

//sword of the cosmos
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_sword>);
mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_sword>, [[null, null, null, null, null, null, null, <ore:ingotInfinity>, <draconicevolution:draconic_staff_of_power>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, <ore:ingotCrystalMatrix>, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, null, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotCrystalMatrix>, null, null, null, null], [<avaritia:resource:5>, null, null, null, null, null, null, null, null]]);