#modloaded extendedcrafting avaritia

//neutronium compressor
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);

//infinity ingot
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);

//neutron collector
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);

//neutronium solar panel
mods.avaritia.ExtremeCrafting.remove(<solarflux:solar_panel_neutronium>);

mods.extendedcrafting.TableCrafting.addShaped(0, <solarflux:solar_panel_neutronium>, [[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotUltimate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, <avaritia:resource:3>, null, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<thermalsolars:blockenderpanel>, <solarflux:solar_panel_chaotic>, <avaritia:resource:3>, <avaritia:resource:2>, <avaritia:resource:5>, <avaritia:resource:2>, <avaritia:resource:3>, <solarflux:solar_panel_chaotic>, <thermalsolars:blockenderpanel>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <avaritia:resource:2>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, null, <avaritia:resource:3>, null, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotUltimate>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

//infinity solar panel
mods.avaritia.ExtremeCrafting.remove(<solarflux:solar_panel_infinity>);

mods.extendedcrafting.TableCrafting.addShaped(0, <solarflux:solar_panel_infinity> * 3, [[null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <thermalsolars:blocksolarpanel103>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <ore:nuggetCosmicNeutronium>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <ore:ingotInfinity>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<thermalsolars:blockenderpanel>, <thermalsolars:blocksolarpanel103>, <ore:nuggetCosmicNeutronium>, <ore:ingotInfinity>, <solarflux:solar_panel_neutronium>, <ore:ingotInfinity>, <ore:nuggetCosmicNeutronium>, <thermalsolars:blocksolarpanel103>, <thermalsolars:blockenderpanel>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, null, <avaritia:resource:2>, <ore:ingotInfinity>, <avaritia:resource:2>, null, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [<ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null, <ore:nuggetCosmicNeutronium>, null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>], [null, <ore:ingotCosmicNeutronium>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <thermalsolars:blocksolarpanel103>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCosmicNeutronium>, null], [null, null, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <thermalsolars:blockenderpanel>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, null, null]]);

//I'm a Potato!
mods.avaritia.ExtremeCrafting.remove(<avaritiatweaks:infinitato>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritiatweaks:infinitato>, [[<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <avaritia:resource:5>, <botania:tinypotato>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>], [<botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>, <botania:tinypotato>]]);

//cosmic meatballs
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);

mods.extendedcrafting.TableCrafting.addShapeless(4, <avaritia:cosmic_meatballs> * 3, [<avaritia:resource:2>, <minecraft:beef>, <minecraft:beef>, <abyssalcraft:antibeef>, <abyssalcraft:antibeef>, <minecraft:chicken>, <minecraft:chicken>, <abyssalcraft:antichicken>, <abyssalcraft:antichicken>, <minecraft:porkchop>, <minecraft:porkchop>, <abyssalcraft:antipork>, <abyssalcraft:antipork>, <minecraft:rabbit>, <minecraft:rabbit>, <minecraft:mutton>, <minecraft:mutton>, <natura:edibles:0>, <natura:edibles:0>, <ore:listAllfishraw>, <ore:listAllfishraw>, <twilightforest:raw_meef>, <twilightforest:raw_meef>, <twilightforest:raw_venison>, <twilightforest:raw_venison>, <netherex:ghast_meat_raw>, <netherex:ghast_meat_raw>]);

//planet eater
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_shovel>, [[null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotInfinity>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null], [null, null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null], [null, <ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null], [<ore:ingotCosmicNeutronium>, null, null, null, null, null, null, null, null]]);

//World Breaker
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_pickaxe>, [[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:blockCrystalMatrix>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>], [<ore:ingotInfinity>, <ore:ingotInfinity>, null, null, <ore:ingotCosmicNeutronium>, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//hoe of green earth
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_hoe>, [[null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [<ore:ingotInfinity>, null, null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null], [null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null]]);

//longbow of the heavens
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_bow>, [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:blockCrystalMatrix>, null, null, null, <ore:blockWool>, null, null, null, null], [<ore:ingotInfinity>, null, null, null, <ore:blockWool>, null, null, null, null], [null, <ore:ingotInfinity>, null, null, <ore:blockWool>, null, null, null, null], [null, null, <ore:ingotInfinity>, null, <ore:blockWool>, null, null, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null, null]]);

//asgardandelion
mods.avaritia.ExtremeCrafting.remove(<botania:specialflower:0>.withTag({type:"asgardandelion"}));

mods.extendedcrafting.TableCrafting.addShaped(4, <botania:specialflower:0>.withTag({type:"asgardandelion"}), [[null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null, null], [null, <avaritia:resource:3>, <avaritia:resource:3>, null, <ore:ingotCosmicNeutronium>, null, <avaritia:resource:3>, <avaritia:resource:3>, null], [<avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <ore:ingotCosmicNeutronium>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>, <avaritia:resource:3>], [null, <avaritia:resource:3>, <avaritia:resource:3>, null, <ore:ingotCosmicNeutronium>, null, <avaritia:resource:3>, <avaritia:resource:3>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//skullfire sword
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:skullfire_sword>, [[null, null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>], [null, null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>], [null, null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null], [null, <ore:bone>, null, <ore:ingotCrystalMatrix>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null], [null, null, <ore:bone>, <ore:powderBlaze>, <ore:ingotCrystalMatrix>, null, null, null, null], [null, null, <ore:logWood>, <ore:bone>, null, null, null, null, null], [null, <ore:logWood>, null, null, <ore:bone>, null, null, null, null], [<ore:netherStar>, null, null, null, null, null, null, null, null]]);

//nature's ruin
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:infinity_axe>, [[null, null, null, <ore:ingotInfinity>, null, null, null, null, null], [null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null, null], [null, null, null, null, null, <ore:ingotInfinity>, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null], [null, null, null, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);

//infinity catalyst
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritia:resource:5>, [[null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <avaritia:cosmic_meatballs>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:ultimate_stew>, <extendedcrafting:singularity_ultimate>, <avaritia:endest_pearl>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], [null, null, <avaritia:resource:7>, <avaritia:resource:7>, <mysticalagradditions:stuff:69>, <avaritia:resource:7>, <avaritia:resource:7>, null, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <avaritia:resource:7>, <ore:ingotCosmicNeutronium>, <avaritia:resource:7>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null, <ore:ingotCosmicNeutronium>, null, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, null, null, null, <ore:ingotCosmicNeutronium>, null, null, null, null]]);

//enhancement crystal
mods.avaritia.ExtremeCrafting.remove(<avaritiatweaks:enhancement_crystal>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritiatweaks:enhancement_crystal>, [[null, null, null, null, <avaritia:resource:4>, null, null, null, null], [null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:5>, <avaritia:resource:1>, <avaritia:resource:5>, <avaritia:resource:4>, null, null], [null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:4>, null, null], [null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null], [null, null, null, null, <avaritia:resource:4>, null, null, null, null]]);

//AvaritiasIO Infinity Capacitor
mods.avaritia.ExtremeCrafting.remove(<avaritiaio:infinitecapacitor>);

mods.extendedcrafting.TableCrafting.addShaped(4, <avaritiaio:infinitecapacitor>, [
[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <avaritia:resource:5>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <avaritia:resource:5>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <avaritia:resource:5>, <ore:ingotCrystalMatrix>, <enderio:item_capacitor_stellar>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <avaritia:resource:5>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotCrystalMatrix>, <avaritia:resource:5>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, <ore:ingotInfinity>, null],
[null, <ore:ingotInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, null],
[null, null, <ore:ingotCosmicNeutronium>, null, null, null, <ore:ingotCosmicNeutronium>, null, null],
[null, null, <ore:ingotCosmicNeutronium>, null, null, null, <ore:ingotCosmicNeutronium>, null, null]]);
