#priority 5
#packmode beast
#modloaded extraplanets

recipes.removeShapeless(<extraplanets:ingot_lead:0>, [<ore:blockLead>]);
recipes.removeShapeless(<extraplanets:tier5_items:7>, [<ore:blockNickel>]);
recipes.removeShapeless(<extraplanets:tier11_items:5>, [<ore:blockPlatinum>]);
recipes.removeShapeless(<extraplanets:ingot_uranium>, [<ore:blockUranium>]);
recipes.removeShapeless(<extraplanets:tier9_items:5>, [<ore:blockTungsten>]);
recipes.removeShapeless(<extraplanets:tier8_items:5>, [<ore:blockZinc>]);
recipes.removeShapeless(<extraplanets:tier5_items:8>, [<ore:blockRedGem>]);
recipes.removeShapeless(<extraplanets:tier7_items:7>, [<ore:blockWhiteGem>]);
recipes.removeShapeless(<extraplanets:tier8_items:6>, [<ore:blockBlueGem>]);
recipes.removeShapeless(<extraplanets:tier4_items:5>, [<ore:blockCarbon>]);
recipes.removeShapeless(<extraplanets:tier5_items:5>, [<ore:blockPalladium>]);
recipes.removeShapeless(<extraplanets:tier6_items:5>, [<ore:blockMagnesium>]);
recipes.removeShapeless(<extraplanets:ingot_mercury:0>, [<ore:blockMercury>]);
recipes.removeShapeless(<extraplanets:tier7_items:5>, [<ore:blockCrystal>]);
recipes.removeShapeless(<extraplanets:tier10_items:5>, [<ore:blockDarkIron>]);
