#packmode normal titan kappa beast
#modloaded extendedcrafting
import mods.extendedcrafting.CompressionCrafting as CC;

//removal
CC.remove(<extendedcrafting:singularity:0>);
CC.remove(<extendedcrafting:singularity:1>);
CC.remove(<extendedcrafting:singularity:2>);
CC.remove(<extendedcrafting:singularity:3>);
CC.remove(<extendedcrafting:singularity:4>);
CC.remove(<extendedcrafting:singularity:5>);
CC.remove(<extendedcrafting:singularity:6>);
CC.remove(<extendedcrafting:singularity:7>);
CC.remove(<extendedcrafting:singularity:16>);
CC.remove(<extendedcrafting:singularity:17>);
CC.remove(<extendedcrafting:singularity:18>);
CC.remove(<extendedcrafting:singularity:19>);
CC.remove(<extendedcrafting:singularity:20>);
CC.remove(<extendedcrafting:singularity:22>);
CC.remove(<extendedcrafting:singularity:23>);
CC.remove(<extendedcrafting:singularity:24>);
CC.remove(<extendedcrafting:singularity:25>);
CC.remove(<extendedcrafting:singularity:26>);
CC.remove(<extendedcrafting:singularity:27>);
CC.remove(<extendedcrafting:singularity:28>);
CC.remove(<extendedcrafting:singularity:29>);
CC.remove(<extendedcrafting:singularity:30>);
CC.remove(<extendedcrafting:singularity:31>);
CC.remove(<extendedcrafting:singularity:32>);
CC.remove(<extendedcrafting:singularity:34>);
CC.remove(<extendedcrafting:singularity:35>);
CC.remove(<extendedcrafting:singularity:48>);
CC.remove(<extendedcrafting:singularity:49>);
CC.remove(<extendedcrafting:singularity:50>);
CC.remove(<extendedcrafting:singularity:64>);
CC.remove(<extendedcrafting:singularity:65>);
CC.remove(<extendedcrafting:singularity:66>);

//addition
CC.addRecipe(<extendedcrafting:singularity:0>, <minecraft:coal_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:1>, <minecraft:iron_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:2>, <minecraft:lapis_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:3>, <minecraft:redstone_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:4>, <minecraft:glowstone>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:5>, <minecraft:gold_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:6>, <minecraft:diamond_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:7>, <minecraft:emerald_block>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:16>, <thermalfoundation:storage:4>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:17>, <thermalfoundation:storage:0>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:18>, <thermalfoundation:storage:1>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:19>, <thermalfoundation:storage_alloy:3>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:20>, <extraplanets:neptune:7>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:22>, <thermalfoundation:storage:2>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:23>, <thermalfoundation:storage:3>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:24>, <thermalfoundation:storage_alloy>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:25>, <thermalfoundation:storage:5>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:26>, <thermalfoundation:storage_alloy:4>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:27>, <thermalfoundation:storage_alloy:1>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:28>, <thermalfoundation:storage_alloy:2>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:29>, <thermalfoundation:storage:8>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:31>, <galacticraftplanets:asteroids_block:7>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:32>, <nuclearcraft:ingot_block:4>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:34>, <thermalfoundation:storage:6>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:35>, <thermalfoundation:storage:7>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:48>, <thermalfoundation:storage_alloy:5>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:49>, <thermalfoundation:storage_alloy:6>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:50>, <thermalfoundation:storage_alloy:7>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:64>, <tconstruct:metal:1>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:65>, <tconstruct:metal:0>, 9001, <extendedcrafting:material:11>, 5000000);
CC.addRecipe(<extendedcrafting:singularity:66>, <tconstruct:metal:2>, 9001, <extendedcrafting:material:11>, 5000000);
