#packmode kappa beast
#modloaded fluidcows cookingforblockheads extendedcrafting
import mods.extendedcrafting.TableCrafting.addShaped as TC;

// Fluid Cow	-	TerraSteel
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "terrasteel"}), [
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <cookingforblockheads:cow_jar>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>],
[<ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>]]);

// Fluid Cow	-	Terrax
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "terrax_fluid"}), [
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <cookingforblockheads:cow_jar>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>],
[<ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>, <ore:blockTerrax>]]);

// Fluid Cow	-	Thorium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "thorium"}), [
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <cookingforblockheads:cow_jar>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>]]);

// Fluid Cow	-	Tiberium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tiberium_fluid"}), [
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <cookingforblockheads:cow_jar>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>],
[<ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>, <ore:blockTiberium>]]);

// Fluid Cow	-	Titanium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "titanium"}), [
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <cookingforblockheads:cow_jar>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>]]);

// Fluid Cow	-	Tritanium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tritanium"}), [
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <cookingforblockheads:cow_jar>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>]]);

// Fluid Cow	-	Tritium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tritium"}), [
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})]]);

// Fluid Cow	-	Tungsten
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tungsten"}), [
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <cookingforblockheads:cow_jar>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>]]);

// Fluid Cow	-	Uranium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "uranium"}), [
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <cookingforblockheads:cow_jar>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>],
[<ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>]]);

// Fluid Cow	-	Uru
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "uru_fluid"}), [
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <cookingforblockheads:cow_jar>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>],
[<ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>, <ore:blockUru>]]);

// Fluid Cow	-	Vibrant Alloy
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "vibrant_alloy"}), [
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <cookingforblockheads:cow_jar>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>],
[<ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>]]);

// Fluid Cow	-	Valyrium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "valyrium_fluid"}), [
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <cookingforblockheads:cow_jar>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>],
[<ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>, <ore:blockValyrium>]]);

// Fluid Cow	-	Vapor of Levity
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "vapor_of_levity"}), [
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})]]);

// Fluid Cow	-	Vibranium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "vibranium_fluid"}), [
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <cookingforblockheads:cow_jar>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>],
[<ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>, <ore:blockVibranium>]]);

// Fluid Cow	-	WitchWater
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "witchwater"}), [
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})]]);

// Fluid Cow	-	Yellorium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "yellorium"}), [
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <cookingforblockheads:cow_jar>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>],
[<ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>]]);

// Fluid Cow	-	Yrdeen
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "yrdeen_fluid"}), [
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <cookingforblockheads:cow_jar>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>],
[<ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>, <ore:blockYrdeen>]]);

// Fluid Cow	-	Zinc
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "zinc"}), [
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <cookingforblockheads:cow_jar>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>]]);
