#packmode kappa beast
#modloaded fluidcows cookingforblockheads extendedcrafting
import mods.extendedcrafting.TableCrafting.addShaped as TC;

// Fluid Cow	-	Naphtha
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "refined_oil"}), [
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "refined_oil", Amount: "1000"})]]);

// Fluid Cow	-	Niob
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "niob_fluid"}), [
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <cookingforblockheads:cow_jar>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>],
[<ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>, <ore:blockNiob>]]);

// Fluid Cow	-	Nitrogen
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "nitrogen"}), [
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <cookingforblockheads:cow_jar>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>],
[<alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>, <alchemistry:element:7>]]);

// Fluid Cow	-	Nucleum
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "nucleum_fluid"}), [
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <cookingforblockheads:cow_jar>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>],
[<ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>, <ore:blockNucleum>]]);

// Fluid Cow	-	Nutrient Destillation
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "nutrient_distillation"}), [
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "nutrient_distillation", Amount: "1000"})]]);

// Fluid Cow	-	Oil (Cool)
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "oil"}), [
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "oil", Amount: "1000"})]]);

// Fluid Cow	-	Osram
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "osram_fluid"}), [
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <cookingforblockheads:cow_jar>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>],
[<ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>, <ore:blockOsram>]]);

// Fluid Cow	-	Ovium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "ovium_fluid"}), [
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <cookingforblockheads:cow_jar>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>],
[<ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>, <ore:blockOvium>]]);

// Fluid Cow	-	Palladium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "palladium_fluid"}), [
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <cookingforblockheads:cow_jar>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>],
[<ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>, <ore:blockPalladium>]]);

// Fluid Cow	-	Plant Oil
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "plantoil"}), [
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plantoil", Amount: "1000"})]]);

// Fluid Cow	-	Plastic
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "plastic"}), [
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:1>, <pneumaticcraft:plastic:3>, <pneumaticcraft:plastic:5>, <pneumaticcraft:plastic:7>, <pneumaticcraft:plastic:9>, <pneumaticcraft:plastic:11>, <pneumaticcraft:plastic:13>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:1>, <pneumaticcraft:plastic:3>, <pneumaticcraft:plastic:5>, <pneumaticcraft:plastic:7>, <pneumaticcraft:plastic:9>, <pneumaticcraft:plastic:11>, <pneumaticcraft:plastic:13>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:1>, <pneumaticcraft:plastic:3>, <pneumaticcraft:plastic:5>, <pneumaticcraft:plastic:7>, <pneumaticcraft:plastic:9>, <pneumaticcraft:plastic:11>, <pneumaticcraft:plastic:13>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:0>, <pneumaticcraft:plastic:0>, <pneumaticcraft:plastic:0>, <cookingforblockheads:cow_jar>, <pneumaticcraft:plastic:15>, <pneumaticcraft:plastic:15>, <pneumaticcraft:plastic:15>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:2>, <pneumaticcraft:plastic:4>, <pneumaticcraft:plastic:6>, <pneumaticcraft:plastic:8>, <pneumaticcraft:plastic:10>, <pneumaticcraft:plastic:12>, <pneumaticcraft:plastic:14>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:2>, <pneumaticcraft:plastic:4>, <pneumaticcraft:plastic:6>, <pneumaticcraft:plastic:8>, <pneumaticcraft:plastic:10>, <pneumaticcraft:plastic:12>, <pneumaticcraft:plastic:14>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <pneumaticcraft:plastic:2>, <pneumaticcraft:plastic:4>, <pneumaticcraft:plastic:6>, <pneumaticcraft:plastic:8>, <pneumaticcraft:plastic:10>, <pneumaticcraft:plastic:12>, <pneumaticcraft:plastic:14>, <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "plastic", Amount: "1000"})]]);

// Fluid Cow	-	Plutonium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "plutonium"}), [
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <cookingforblockheads:cow_jar>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>],
[<alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>, <alchemistry:element:94>]]);

// Fluid Cow	-	Poison
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "poison"}), [
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <cookingforblockheads:cow_jar>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>],
[<minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>, <minecraft:poisonous_potato>]]);

// Fluid Cow	-	Potassium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "potassium"}), [
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <cookingforblockheads:cow_jar>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>],
[<alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>, <alchemistry:element:19>]]);

// Fluid Cow	-	Primal Mana
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "mana"}), [
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "mana", Amount: "1000"})]]);

// Fluid Cow	-	Prometheum
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "prometheum_fluid"}), [
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <cookingforblockheads:cow_jar>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>],
[<ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>, <ore:blockPrometheum>]]);

// Fluid Cow	-	Protein
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "if.protein"}), [
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <cookingforblockheads:cow_jar>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>],
[<alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>, <alchemistry:compound:9>]]);

// Fluid Cow	-	Proxii
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "proxii_fluid"}), [
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <cookingforblockheads:cow_jar>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>],
[<ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>, <ore:blockProxii>]]);

// Fluid Cow	-	Prudentium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "prudentium"}), [
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <cookingforblockheads:cow_jar>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>],
[<ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>, <ore:blockPrudentium>]]);

// Fluid Cow	-	PsiMetal
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "psimetal"}), [
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <cookingforblockheads:cow_jar>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>],
[<ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>, <ore:blockPsiMetal>]]);

// Fluid Cow	-	Quartz
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "quartz"}), [
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <cookingforblockheads:cow_jar>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>],
[<ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>]]);
