#packmode kappa mythic beast
#modloaded fluidcows cookingforblockheads extendedcrafting
import mods.extendedcrafting.TableCrafting.addShaped as TC;

// Fluid Cow	-	Thorium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "thorium"}), [
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <cookingforblockheads:cow_jar>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>],
[<ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>, <ore:blockThorium>]]);

// Fluid Cow	-	Titanium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "titanium"}), [
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <cookingforblockheads:cow_jar>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>],
[<ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>]]);

// Fluid Cow	-	Tritanium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tritanium"}), [
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <cookingforblockheads:cow_jar>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>],
[<ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>, <ore:blockTritanium>]]);

// Fluid Cow	-	Tritium
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tritium"}), [
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "tritium", Amount: "1000"})]]);

// Fluid Cow	-	Tungsten
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "tungsten"}), [
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <cookingforblockheads:cow_jar>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>],
[<ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>, <ore:blockTungsten>]]);

// Fluid Cow	-	Vapor of Levity
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "vapor_of_levity"}), [
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "vapor_of_levity", Amount: "1000"})]]);

// Fluid Cow	-	WitchWater
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "witchwater"}), [
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <cookingforblockheads:cow_jar>, <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})],
[<forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"}), <forge:bucketfilled>.withTag({FluidName: "witchwater", Amount: "1000"})]]);

// Fluid Cow	-	Zinc
TC(0, <fluidcows:cow_displayer>.withTag({fluid: "zinc"}), [
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <cookingforblockheads:cow_jar>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>],
[<ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>, <ore:blockZinc>]]);
