give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"abyssalnite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"abyssum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"adamantine_metal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"alduorite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"aluminum_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"aluminum_brass_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"alumite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"alugentum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"abyssum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"adamant_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"adamantine_metal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"amber_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium241_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium241oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium242_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium242base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium242oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium243_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"americium243oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"amordrine_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"angmallen_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"aquamarine_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ardite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"arsenic_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"astral_silver_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"astrium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"atlarus_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"aurorium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"awakened_draconium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"baronyte_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"basalt_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"basalt_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"basalz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"beet_root_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"berkelium247_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"berkelium247oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"berkelium248_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"berkelium248base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"berkelium248oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"beryllium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"black_iron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"black_quartz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"black_steel_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blaze_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blitz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blizz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blue_diamond_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blue_gem_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"blutonium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"borer_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boron10_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boron11_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boronarsenide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boronnitride_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"boundmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"brass_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"bronze_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium249_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium249base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium249oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium250_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium250oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium251_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium251base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium251oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium252_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"californium252oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"carbon_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"carmot_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"carobbiite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"celenegil_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"certus_quartz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ceruclase_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"chaoticmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"chicken_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"chocolate_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"cobalt_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"cocoabutter_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"constructionalloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"coal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"compressed_iron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"conductive_iron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"constantan_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"copper_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"coralium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"cow_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"creeper_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crudesteel_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystalflux_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystalline_alloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystalline_pink_slime_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystalmatrix_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"crystaltine_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium243_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium243base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium243oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium245_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium245base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium245oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium246_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium246oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium247_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium247base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"curium247oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"cyanite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"damascus_steel_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"darkchocolate_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dark_iron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dark_steel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dawnstone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"demonicmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"deep_iron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"desh_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"desichalkos_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"diamond_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dilithium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dimensional_shard_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dirt_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"draconium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"draconic_metal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dragon_egg_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dreadium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"duranite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dye_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"dyonite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"eezo_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"electrical_steel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"electrotine_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"electrotine_alloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"electrum_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"elementium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"emerald_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"enchantedmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ender_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ender_biotite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"enderman_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"enderium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"end_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"end_steel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"energetic_alloy_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"energetic_silver_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"erebus_mandrake_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"essencemetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ethaxium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"etherium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"evilmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"eximite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"experience_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"extreme_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ferroboron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fire_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fiery_ingot_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"flint_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fluix_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fluorite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fluxed_electrum_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"fractum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"friscion_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"gaia_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"garfax_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ghast_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"gold_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"glowstone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"glowstone_ingot_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"grains_of_infinity_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"graphite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"green_diamond_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"guardian_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"haderoth_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"hardcarbon_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"hepatizon_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"hemp_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"hop_graphite_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"hSLA_steel_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ice_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ignatius_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ignitz_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"imperomite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"infinity_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"inolashite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"infuscolium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"invar_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"iox_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"iridium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"iron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ironwood_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"jade_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"jauxum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"kalendrite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"karmesine_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"kelline_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"knightmetal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"knightslime_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"krik_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"landium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lapis_lazuli_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lead_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"leadplatinum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lemurite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"limestone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lithium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lithium6_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lithium7_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lithium_manganese_dioxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"liquified_coralium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ludicrite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lumium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lumix_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lunar_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"lutetium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"magnesium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"magnesium_diboride_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"manasteel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"manganese_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"manganesedioxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"manganeseoxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"manyullyn_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"marble_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"marshmallow_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"melodic_alloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"meteoric_iron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"meteorite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"mercury_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"meutoite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"midasium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"mirion_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"mithril_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"moon_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"morganine_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"mystical_flower_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nature_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nepptunium236_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nepptunium236base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nepptunium236oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nepptunium237_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nepptunium237oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nether_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nether_quartz_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nether_star_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"neutronium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nickel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nihilite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"niob_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"niter_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"nucleum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"obsidian_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"obsidian_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"obsidiorite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"orichalcum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"osgloglas_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"osmium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"osmiridium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"osram_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"oureclase_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ovium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"palladium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"peridot_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"phosphorus_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"pig_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"pigiron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"platinum_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium238_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium238oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium239_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium239base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium239oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium241_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium241base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium241oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium242_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"plutonium242oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"potash_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"prometheum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"proxii_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"pulsating_iron_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"pumpkin_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"purple_diamond_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"quicksilver_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"rabbit_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"racheline_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"red_diamond_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"red_gem_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"redstone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"redstone_alloy_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"red_alloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"refined_obsidian_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"reinforced_obsidian_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"rhodochrosite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"rock_crystal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"rubber_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"rubracium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ruby_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"saltpeter_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sanguinite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sapphire_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"seismum_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sentientmetal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"shadow_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"shadow_iron_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"shadow_steel_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"shibuichi_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sheep_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sicsiccmc_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"signalum_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"silicon_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"silicon_carbide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"silver_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"skeleton_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sky_stone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"slate_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"slime_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"solarium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"soularium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"spider_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"starmetal_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"stellaralloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"steel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"steeleaf_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"stone_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"sulfur_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tartarite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"terrasteel_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"terrax_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tiberium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tier6_inferium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tin_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tinsilver_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"titanium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"titanium_aluminide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"titanium_iridium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"triberium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tritonite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thermoconducting_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thoriumoxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium230_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium230oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium232_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium232base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"thorium232oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tough_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"tungsten_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"ultimate_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"unstable_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"unsweetenedchocolate_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uraniu_moxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium233_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium233base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium233oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium235_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium235base_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium235oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium238_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uranium238oxide_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"uru_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"valyrium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"vibranium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"vibrant_alloy_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"villiaumite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"violium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"vivid_alloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"vulcanite_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"vyroxeres_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"water_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"white_gem_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"wither_skeleton_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"wood_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"wyvern_metal_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"yellorium_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"yellow_diamond_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"yrdeen_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"zinc_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"zircaloy_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"zirconium_mystical_plant",agri_growth:10b}
give speecker agricraft:clipping 2 1 {agri_analyzed:1b,agri_strength:10b,agri_gain:10b,agri_seed:"zombie_plant",agri_growth:10b}
